/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Cr1100pk0fetchMenuItemsResponse implements Serializable {


    @ColumnAlias("poutMenuItems")
    private List<Cr1100pk0fetchMenuItemsResponsePoutMenuItems> poutMenuItems;

    public List<Cr1100pk0fetchMenuItemsResponsePoutMenuItems> getPoutMenuItems() {
        return this.poutMenuItems;
    }

    public void setPoutMenuItems(List<Cr1100pk0fetchMenuItemsResponsePoutMenuItems> poutMenuItems) {
        this.poutMenuItems = poutMenuItems;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Cr1100pk0fetchMenuItemsResponse)) return false;
        final Cr1100pk0fetchMenuItemsResponse cr1100pk0fetchMenuItemsResponse = (Cr1100pk0fetchMenuItemsResponse) o;
        return Objects.equals(getPoutMenuItems(), cr1100pk0fetchMenuItemsResponse.getPoutMenuItems());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMenuItems());
    }
}