/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Cr1100pk0fetchSizesResponse implements Serializable {


    @ColumnAlias("poutSizeList")
    private List<Cr1100pk0fetchSizesResponsePoutSizeList> poutSizeList;

    public List<Cr1100pk0fetchSizesResponsePoutSizeList> getPoutSizeList() {
        return this.poutSizeList;
    }

    public void setPoutSizeList(List<Cr1100pk0fetchSizesResponsePoutSizeList> poutSizeList) {
        this.poutSizeList = poutSizeList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Cr1100pk0fetchSizesResponse)) return false;
        final Cr1100pk0fetchSizesResponse cr1100pk0fetchSizesResponse = (Cr1100pk0fetchSizesResponse) o;
        return Objects.equals(getPoutSizeList(), cr1100pk0fetchSizesResponse.getPoutSizeList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutSizeList());
    }
}