/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr800pk0ProvpklCartonDefResponsePoutCtntype implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("CTNTYPE")
    private String ctntype;

    @ColumnAlias("CTNDES")
    private String ctndes;

    @ColumnAlias("GRSWGT")
    private Float grswgt;

    @ColumnAlias("CTNWGT")
    private Float ctnwgt;

    @ColumnAlias("CTNDIMENSION")
    private String ctndimension;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getCtntype() {
        return this.ctntype;
    }

    public void setCtntype(String ctntype) {
        this.ctntype = ctntype;
    }

    public String getCtndes() {
        return this.ctndes;
    }

    public void setCtndes(String ctndes) {
        this.ctndes = ctndes;
    }

    public Float getGrswgt() {
        return this.grswgt;
    }

    public void setGrswgt(Float grswgt) {
        this.grswgt = grswgt;
    }

    public Float getCtnwgt() {
        return this.ctnwgt;
    }

    public void setCtnwgt(Float ctnwgt) {
        this.ctnwgt = ctnwgt;
    }

    public String getCtndimension() {
        return this.ctndimension;
    }

    public void setCtndimension(String ctndimension) {
        this.ctndimension = ctndimension;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr800pk0ProvpklCartonDefResponsePoutCtntype)) return false;
        final ProcCr800pk0ProvpklCartonDefResponsePoutCtntype procCr800pk0provpklCartonDefResponsePoutCtntype = (ProcCr800pk0ProvpklCartonDefResponsePoutCtntype) o;
        return Objects.equals(getOrdnum(), procCr800pk0provpklCartonDefResponsePoutCtntype.getOrdnum()) &&
                Objects.equals(getShpnum(), procCr800pk0provpklCartonDefResponsePoutCtntype.getShpnum()) &&
                Objects.equals(getCtntype(), procCr800pk0provpklCartonDefResponsePoutCtntype.getCtntype()) &&
                Objects.equals(getCtndes(), procCr800pk0provpklCartonDefResponsePoutCtntype.getCtndes()) &&
                Objects.equals(getGrswgt(), procCr800pk0provpklCartonDefResponsePoutCtntype.getGrswgt()) &&
                Objects.equals(getCtnwgt(), procCr800pk0provpklCartonDefResponsePoutCtntype.getCtnwgt()) &&
                Objects.equals(getCtndimension(), procCr800pk0provpklCartonDefResponsePoutCtntype.getCtndimension());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getShpnum(),
                getCtntype(),
                getCtndes(),
                getGrswgt(),
                getCtnwgt(),
                getCtndimension());
    }
}