/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("MRCID")
    private String mrcid;

    @ColumnAlias("SSN")
    private String ssn;

    @ColumnAlias("SSHPDAT")
    private LocalDateTime sshpdat;

    @ColumnAlias("SHPMOD")
    private String shpmod;

    @ColumnAlias("QTYORD")
    private Integer qtyord;

    @ColumnAlias("PCKUNT")
    private Byte pckunt;

    @ColumnAlias("MAKLCN")
    private String maklcn;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("ORDSTS")
    private String ordsts;

    @ColumnAlias("PCKDES")
    private String pckdes;

    @ColumnAlias("STYDES")
    private String stydes;

    @ColumnAlias("MERCHNAME")
    private String merchname;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getMrcid() {
        return this.mrcid;
    }

    public void setMrcid(String mrcid) {
        this.mrcid = mrcid;
    }

    public String getSsn() {
        return this.ssn;
    }

    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    public LocalDateTime getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(LocalDateTime sshpdat) {
        this.sshpdat = sshpdat;
    }

    public String getShpmod() {
        return this.shpmod;
    }

    public void setShpmod(String shpmod) {
        this.shpmod = shpmod;
    }

    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    public Byte getPckunt() {
        return this.pckunt;
    }

    public void setPckunt(Byte pckunt) {
        this.pckunt = pckunt;
    }

    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getOrdsts() {
        return this.ordsts;
    }

    public void setOrdsts(String ordsts) {
        this.ordsts = ordsts;
    }

    public String getPckdes() {
        return this.pckdes;
    }

    public void setPckdes(String pckdes) {
        this.pckdes = pckdes;
    }

    public String getStydes() {
        return this.stydes;
    }

    public void setStydes(String stydes) {
        this.stydes = stydes;
    }

    public String getMerchname() {
        return this.merchname;
    }

    public void setMerchname(String merchname) {
        this.merchname = merchname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet)) return false;
        final ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet procCr1100pk0getCr210orderDetResponsePoutOrderDet = (ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet) o;
        return Objects.equals(getOrdnum(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getOrdnum()) &&
                Objects.equals(getMrcid(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getMrcid()) &&
                Objects.equals(getSsn(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getSsn()) &&
                Objects.equals(getSshpdat(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getSshpdat()) &&
                Objects.equals(getShpmod(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getShpmod()) &&
                Objects.equals(getQtyord(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getQtyord()) &&
                Objects.equals(getPckunt(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getPckunt()) &&
                Objects.equals(getMaklcn(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getMaklcn()) &&
                Objects.equals(getClicod(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getClicod()) &&
                Objects.equals(getOrdsts(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getOrdsts()) &&
                Objects.equals(getPckdes(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getPckdes()) &&
                Objects.equals(getStydes(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getStydes()) &&
                Objects.equals(getMerchname(), procCr1100pk0getCr210orderDetResponsePoutOrderDet.getMerchname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getMrcid(),
                getSsn(),
                getSshpdat(),
                getShpmod(),
                getQtyord(),
                getPckunt(),
                getMaklcn(),
                getClicod(),
                getOrdsts(),
                getPckdes(),
                getStydes(),
                getMerchname());
    }
}