/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr800pk0NewPshpBulkInsCtnResponse implements Serializable {


    @ColumnAlias("poutPshpnum")
    private String poutPshpnum;

    public String getPoutPshpnum() {
        return this.poutPshpnum;
    }

    public void setPoutPshpnum(String poutPshpnum) {
        this.poutPshpnum = poutPshpnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr800pk0NewPshpBulkInsCtnResponse)) return false;
        final ProcCr800pk0NewPshpBulkInsCtnResponse procCr800pk0newPshpBulkInsCtnResponse = (ProcCr800pk0NewPshpBulkInsCtnResponse) o;
        return Objects.equals(getPoutPshpnum(), procCr800pk0newPshpBulkInsCtnResponse.getPoutPshpnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutPshpnum());
    }
}