/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0GetOrt205detResponse implements Serializable {


    @ColumnAlias("poutShpDet")
    private List<ProcCr1100pk0GetOrt205detResponsePoutShpDet> poutShpDet;

    public List<ProcCr1100pk0GetOrt205detResponsePoutShpDet> getPoutShpDet() {
        return this.poutShpDet;
    }

    public void setPoutShpDet(List<ProcCr1100pk0GetOrt205detResponsePoutShpDet> poutShpDet) {
        this.poutShpDet = poutShpDet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0GetOrt205detResponse)) return false;
        final ProcCr1100pk0GetOrt205detResponse procCr1100pk0getOrt205detResponse = (ProcCr1100pk0GetOrt205detResponse) o;
        return Objects.equals(getPoutShpDet(), procCr1100pk0getOrt205detResponse.getPoutShpDet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutShpDet());
    }
}