/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0GetCartoningGmtClrDetResponse implements Serializable {


    @ColumnAlias("poutGmtclrList")
    private List<ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList> poutGmtclrList;

    public List<ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList> getPoutGmtclrList() {
        return this.poutGmtclrList;
    }

    public void setPoutGmtclrList(List<ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList> poutGmtclrList) {
        this.poutGmtclrList = poutGmtclrList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0GetCartoningGmtClrDetResponse)) return false;
        final ProcCr1100pk0GetCartoningGmtClrDetResponse procCr1100pk0getCartoningGmtClrDetResponse = (ProcCr1100pk0GetCartoningGmtClrDetResponse) o;
        return Objects.equals(getPoutGmtclrList(), procCr1100pk0getCartoningGmtClrDetResponse.getPoutGmtclrList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutGmtclrList());
    }
}