/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0GetOrt205detResponsePoutShpDet implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("SSHPDAT")
    private LocalDateTime sshpdat;

    @ColumnAlias("PCKTYP")
    private String pcktyp;

    @ColumnAlias("SHPMOD")
    private String shpmod;

    @ColumnAlias("ASHPDAT")
    private LocalDateTime ashpdat;

    @ColumnAlias("CLIPCKTYP")
    private String clipcktyp;

    @ColumnAlias("CLIONUM")
    private String clionum;

    @ColumnAlias("SHPDST")
    private String shpdst;

    @ColumnAlias("QTYORD")
    private Integer qtyord;

    @ColumnAlias("REM")
    private String rem;

    @ColumnAlias("QTYDES")
    private String qtydes;

    @ColumnAlias("SEQCODCOLUMNTITLE")
    private String seqcodcolumntitle;

    @ColumnAlias("W_PCKDES")
    private String wpckdes;

    @ColumnAlias("W_CLICOD")
    private String wclicod;

    @ColumnAlias("W_DCDAT")
    private LocalDateTime wdcdat;

    @ColumnAlias("W_PCKUNT")
    private Byte wpckunt;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public LocalDateTime getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(LocalDateTime sshpdat) {
        this.sshpdat = sshpdat;
    }

    public String getPcktyp() {
        return this.pcktyp;
    }

    public void setPcktyp(String pcktyp) {
        this.pcktyp = pcktyp;
    }

    public String getShpmod() {
        return this.shpmod;
    }

    public void setShpmod(String shpmod) {
        this.shpmod = shpmod;
    }

    public LocalDateTime getAshpdat() {
        return this.ashpdat;
    }

    public void setAshpdat(LocalDateTime ashpdat) {
        this.ashpdat = ashpdat;
    }

    public String getClipcktyp() {
        return this.clipcktyp;
    }

    public void setClipcktyp(String clipcktyp) {
        this.clipcktyp = clipcktyp;
    }

    public String getClionum() {
        return this.clionum;
    }

    public void setClionum(String clionum) {
        this.clionum = clionum;
    }

    public String getShpdst() {
        return this.shpdst;
    }

    public void setShpdst(String shpdst) {
        this.shpdst = shpdst;
    }

    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    public String getRem() {
        return this.rem;
    }

    public void setRem(String rem) {
        this.rem = rem;
    }

    public String getQtydes() {
        return this.qtydes;
    }

    public void setQtydes(String qtydes) {
        this.qtydes = qtydes;
    }

    public String getSeqcodcolumntitle() {
        return this.seqcodcolumntitle;
    }

    public void setSeqcodcolumntitle(String seqcodcolumntitle) {
        this.seqcodcolumntitle = seqcodcolumntitle;
    }

    public String getWpckdes() {
        return this.wpckdes;
    }

    public void setWpckdes(String wpckdes) {
        this.wpckdes = wpckdes;
    }

    public String getWclicod() {
        return this.wclicod;
    }

    public void setWclicod(String wclicod) {
        this.wclicod = wclicod;
    }

    public LocalDateTime getWdcdat() {
        return this.wdcdat;
    }

    public void setWdcdat(LocalDateTime wdcdat) {
        this.wdcdat = wdcdat;
    }

    public Byte getWpckunt() {
        return this.wpckunt;
    }

    public void setWpckunt(Byte wpckunt) {
        this.wpckunt = wpckunt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0GetOrt205detResponsePoutShpDet)) return false;
        final ProcCr1100pk0GetOrt205detResponsePoutShpDet procCr1100pk0getOrt205detResponsePoutShpDet = (ProcCr1100pk0GetOrt205detResponsePoutShpDet) o;
        return Objects.equals(getOrdnum(), procCr1100pk0getOrt205detResponsePoutShpDet.getOrdnum()) &&
                Objects.equals(getShpnum(), procCr1100pk0getOrt205detResponsePoutShpDet.getShpnum()) &&
                Objects.equals(getSshpdat(), procCr1100pk0getOrt205detResponsePoutShpDet.getSshpdat()) &&
                Objects.equals(getPcktyp(), procCr1100pk0getOrt205detResponsePoutShpDet.getPcktyp()) &&
                Objects.equals(getShpmod(), procCr1100pk0getOrt205detResponsePoutShpDet.getShpmod()) &&
                Objects.equals(getAshpdat(), procCr1100pk0getOrt205detResponsePoutShpDet.getAshpdat()) &&
                Objects.equals(getClipcktyp(), procCr1100pk0getOrt205detResponsePoutShpDet.getClipcktyp()) &&
                Objects.equals(getClionum(), procCr1100pk0getOrt205detResponsePoutShpDet.getClionum()) &&
                Objects.equals(getShpdst(), procCr1100pk0getOrt205detResponsePoutShpDet.getShpdst()) &&
                Objects.equals(getQtyord(), procCr1100pk0getOrt205detResponsePoutShpDet.getQtyord()) &&
                Objects.equals(getRem(), procCr1100pk0getOrt205detResponsePoutShpDet.getRem()) &&
                Objects.equals(getQtydes(), procCr1100pk0getOrt205detResponsePoutShpDet.getQtydes()) &&
                Objects.equals(getSeqcodcolumntitle(), procCr1100pk0getOrt205detResponsePoutShpDet.getSeqcodcolumntitle()) &&
                Objects.equals(getWpckdes(), procCr1100pk0getOrt205detResponsePoutShpDet.getWpckdes()) &&
                Objects.equals(getWclicod(), procCr1100pk0getOrt205detResponsePoutShpDet.getWclicod()) &&
                Objects.equals(getWdcdat(), procCr1100pk0getOrt205detResponsePoutShpDet.getWdcdat()) &&
                Objects.equals(getWpckunt(), procCr1100pk0getOrt205detResponsePoutShpDet.getWpckunt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getShpnum(),
                getSshpdat(),
                getPcktyp(),
                getShpmod(),
                getAshpdat(),
                getClipcktyp(),
                getClionum(),
                getShpdst(),
                getQtyord(),
                getRem(),
                getQtydes(),
                getSeqcodcolumntitle(),
                getWpckdes(),
                getWclicod(),
                getWdcdat(),
                getWpckunt());
    }
}