/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0Cr600pcsCartonedResponsePoutPshpList implements Serializable {


    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("PSHPNUM")
    private String pshpnum;

    @ColumnAlias("SECTION")
    private String section;

    @ColumnAlias("SCANDAT")
    private LocalDateTime scandat;

    @ColumnAlias("UNIT")
    private String unit;

    @ColumnAlias("CTNS")
    private BigDecimal ctns;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("TRNCODE")
    private String trncode;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("W_DELIVDAT")
    private LocalDateTime wdelivdat;

    @ColumnAlias("QTYORD1")
    private BigInteger qtyord1;

    @ColumnAlias("QTYORD2")
    private BigInteger qtyord2;

    @ColumnAlias("QTYORD3")
    private BigInteger qtyord3;

    @ColumnAlias("QTYORD4")
    private BigInteger qtyord4;

    @ColumnAlias("QTYORD5")
    private BigInteger qtyord5;

    @ColumnAlias("QTYORD6")
    private BigInteger qtyord6;

    @ColumnAlias("QTYORD7")
    private BigInteger qtyord7;

    @ColumnAlias("QTYORD8")
    private BigInteger qtyord8;

    @ColumnAlias("QTYORD9")
    private BigInteger qtyord9;

    @ColumnAlias("QTYORD10")
    private BigInteger qtyord10;

    @ColumnAlias("QTYORD11")
    private BigInteger qtyord11;

    @ColumnAlias("QTYORD12")
    private BigInteger qtyord12;

    @ColumnAlias("QTYORD13")
    private BigInteger qtyord13;

    @ColumnAlias("QTYORD14")
    private BigInteger qtyord14;

    @ColumnAlias("QTYORD15")
    private BigInteger qtyord15;

    @ColumnAlias("QTYORD16")
    private BigInteger qtyord16;

    @ColumnAlias("W_TOTAL_QTYORD")
    private BigInteger wtotalQtyord;

    @ColumnAlias("TOTPCS")
    private BigDecimal totpcs;

    @ColumnAlias("PCS1")
    private BigDecimal pcs1;

    @ColumnAlias("PCS2")
    private BigDecimal pcs2;

    @ColumnAlias("PCS3")
    private BigDecimal pcs3;

    @ColumnAlias("PCS4")
    private BigDecimal pcs4;

    @ColumnAlias("PCS5")
    private BigDecimal pcs5;

    @ColumnAlias("PCS6")
    private BigDecimal pcs6;

    @ColumnAlias("PCS7")
    private BigDecimal pcs7;

    @ColumnAlias("PCS8")
    private BigDecimal pcs8;

    @ColumnAlias("PCS9")
    private BigDecimal pcs9;

    @ColumnAlias("PCS10")
    private BigDecimal pcs10;

    @ColumnAlias("PCS11")
    private BigDecimal pcs11;

    @ColumnAlias("PCS12")
    private BigDecimal pcs12;

    @ColumnAlias("PCS13")
    private BigDecimal pcs13;

    @ColumnAlias("PCS14")
    private BigDecimal pcs14;

    @ColumnAlias("PCS15")
    private BigDecimal pcs15;

    @ColumnAlias("PCS16")
    private BigDecimal pcs16;

    @ColumnAlias("W_TOTAL_TOTPCS")
    private BigInteger wtotalTotpcs;

    @ColumnAlias("W_TOTAL_BAL")
    private BigInteger wtotalBal;

    @ColumnAlias("W_TOTAL_COMP")
    private BigDecimal wtotalComp;

    @ColumnAlias("TOTPCS1")
    private BigInteger totpcs1;

    @ColumnAlias("TOTPCS2")
    private BigInteger totpcs2;

    @ColumnAlias("TOTPCS3")
    private BigInteger totpcs3;

    @ColumnAlias("TOTPCS4")
    private BigInteger totpcs4;

    @ColumnAlias("TOTPCS5")
    private BigInteger totpcs5;

    @ColumnAlias("TOTPCS6")
    private BigInteger totpcs6;

    @ColumnAlias("TOTPCS7")
    private BigInteger totpcs7;

    @ColumnAlias("TOTPCS8")
    private BigInteger totpcs8;

    @ColumnAlias("TOTPCS9")
    private BigInteger totpcs9;

    @ColumnAlias("TOTPCS10")
    private BigInteger totpcs10;

    @ColumnAlias("TOTPCS11")
    private BigInteger totpcs11;

    @ColumnAlias("TOTPCS12")
    private BigInteger totpcs12;

    @ColumnAlias("TOTPCS13")
    private BigInteger totpcs13;

    @ColumnAlias("TOTPCS14")
    private BigInteger totpcs14;

    @ColumnAlias("TOTPCS15")
    private BigInteger totpcs15;

    @ColumnAlias("TOTPCS16")
    private BigInteger totpcs16;

    @ColumnAlias("BAL1")
    private BigInteger bal1;

    @ColumnAlias("BAL2")
    private BigInteger bal2;

    @ColumnAlias("BAL3")
    private BigInteger bal3;

    @ColumnAlias("BAL4")
    private BigInteger bal4;

    @ColumnAlias("BAL5")
    private BigInteger bal5;

    @ColumnAlias("BAL6")
    private BigInteger bal6;

    @ColumnAlias("BAL7")
    private BigInteger bal7;

    @ColumnAlias("BAL8")
    private BigInteger bal8;

    @ColumnAlias("BAL9")
    private BigInteger bal9;

    @ColumnAlias("BAL10")
    private BigInteger bal10;

    @ColumnAlias("BAL11")
    private BigInteger bal11;

    @ColumnAlias("BAL12")
    private BigInteger bal12;

    @ColumnAlias("BAL13")
    private BigInteger bal13;

    @ColumnAlias("BAL14")
    private BigInteger bal14;

    @ColumnAlias("BAL15")
    private BigInteger bal15;

    @ColumnAlias("BAL16")
    private BigInteger bal16;

    @ColumnAlias("COMP1")
    private BigDecimal comp1;

    @ColumnAlias("COMP2")
    private BigDecimal comp2;

    @ColumnAlias("COMP3")
    private BigDecimal comp3;

    @ColumnAlias("COMP4")
    private BigDecimal comp4;

    @ColumnAlias("COMP5")
    private BigDecimal comp5;

    @ColumnAlias("COMP6")
    private BigDecimal comp6;

    @ColumnAlias("COMP7")
    private BigDecimal comp7;

    @ColumnAlias("COMP8")
    private BigDecimal comp8;

    @ColumnAlias("COMP9")
    private BigDecimal comp9;

    @ColumnAlias("COMP10")
    private BigDecimal comp10;

    @ColumnAlias("COMP11")
    private BigDecimal comp11;

    @ColumnAlias("COMP12")
    private BigDecimal comp12;

    @ColumnAlias("COMP13")
    private BigDecimal comp13;

    @ColumnAlias("COMP14")
    private BigDecimal comp14;

    @ColumnAlias("COMP15")
    private BigDecimal comp15;

    @ColumnAlias("COMP16")
    private BigDecimal comp16;

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public String getSection() {
        return this.section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public LocalDateTime getScandat() {
        return this.scandat;
    }

    public void setScandat(LocalDateTime scandat) {
        this.scandat = scandat;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public BigDecimal getCtns() {
        return this.ctns;
    }

    public void setCtns(BigDecimal ctns) {
        this.ctns = ctns;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getTrncode() {
        return this.trncode;
    }

    public void setTrncode(String trncode) {
        this.trncode = trncode;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getWdelivdat() {
        return this.wdelivdat;
    }

    public void setWdelivdat(LocalDateTime wdelivdat) {
        this.wdelivdat = wdelivdat;
    }

    public BigInteger getQtyord1() {
        return this.qtyord1;
    }

    public void setQtyord1(BigInteger qtyord1) {
        this.qtyord1 = qtyord1;
    }

    public BigInteger getQtyord2() {
        return this.qtyord2;
    }

    public void setQtyord2(BigInteger qtyord2) {
        this.qtyord2 = qtyord2;
    }

    public BigInteger getQtyord3() {
        return this.qtyord3;
    }

    public void setQtyord3(BigInteger qtyord3) {
        this.qtyord3 = qtyord3;
    }

    public BigInteger getQtyord4() {
        return this.qtyord4;
    }

    public void setQtyord4(BigInteger qtyord4) {
        this.qtyord4 = qtyord4;
    }

    public BigInteger getQtyord5() {
        return this.qtyord5;
    }

    public void setQtyord5(BigInteger qtyord5) {
        this.qtyord5 = qtyord5;
    }

    public BigInteger getQtyord6() {
        return this.qtyord6;
    }

    public void setQtyord6(BigInteger qtyord6) {
        this.qtyord6 = qtyord6;
    }

    public BigInteger getQtyord7() {
        return this.qtyord7;
    }

    public void setQtyord7(BigInteger qtyord7) {
        this.qtyord7 = qtyord7;
    }

    public BigInteger getQtyord8() {
        return this.qtyord8;
    }

    public void setQtyord8(BigInteger qtyord8) {
        this.qtyord8 = qtyord8;
    }

    public BigInteger getQtyord9() {
        return this.qtyord9;
    }

    public void setQtyord9(BigInteger qtyord9) {
        this.qtyord9 = qtyord9;
    }

    public BigInteger getQtyord10() {
        return this.qtyord10;
    }

    public void setQtyord10(BigInteger qtyord10) {
        this.qtyord10 = qtyord10;
    }

    public BigInteger getQtyord11() {
        return this.qtyord11;
    }

    public void setQtyord11(BigInteger qtyord11) {
        this.qtyord11 = qtyord11;
    }

    public BigInteger getQtyord12() {
        return this.qtyord12;
    }

    public void setQtyord12(BigInteger qtyord12) {
        this.qtyord12 = qtyord12;
    }

    public BigInteger getQtyord13() {
        return this.qtyord13;
    }

    public void setQtyord13(BigInteger qtyord13) {
        this.qtyord13 = qtyord13;
    }

    public BigInteger getQtyord14() {
        return this.qtyord14;
    }

    public void setQtyord14(BigInteger qtyord14) {
        this.qtyord14 = qtyord14;
    }

    public BigInteger getQtyord15() {
        return this.qtyord15;
    }

    public void setQtyord15(BigInteger qtyord15) {
        this.qtyord15 = qtyord15;
    }

    public BigInteger getQtyord16() {
        return this.qtyord16;
    }

    public void setQtyord16(BigInteger qtyord16) {
        this.qtyord16 = qtyord16;
    }

    public BigInteger getWtotalQtyord() {
        return this.wtotalQtyord;
    }

    public void setWtotalQtyord(BigInteger wtotalQtyord) {
        this.wtotalQtyord = wtotalQtyord;
    }

    public BigDecimal getTotpcs() {
        return this.totpcs;
    }

    public void setTotpcs(BigDecimal totpcs) {
        this.totpcs = totpcs;
    }

    public BigDecimal getPcs1() {
        return this.pcs1;
    }

    public void setPcs1(BigDecimal pcs1) {
        this.pcs1 = pcs1;
    }

    public BigDecimal getPcs2() {
        return this.pcs2;
    }

    public void setPcs2(BigDecimal pcs2) {
        this.pcs2 = pcs2;
    }

    public BigDecimal getPcs3() {
        return this.pcs3;
    }

    public void setPcs3(BigDecimal pcs3) {
        this.pcs3 = pcs3;
    }

    public BigDecimal getPcs4() {
        return this.pcs4;
    }

    public void setPcs4(BigDecimal pcs4) {
        this.pcs4 = pcs4;
    }

    public BigDecimal getPcs5() {
        return this.pcs5;
    }

    public void setPcs5(BigDecimal pcs5) {
        this.pcs5 = pcs5;
    }

    public BigDecimal getPcs6() {
        return this.pcs6;
    }

    public void setPcs6(BigDecimal pcs6) {
        this.pcs6 = pcs6;
    }

    public BigDecimal getPcs7() {
        return this.pcs7;
    }

    public void setPcs7(BigDecimal pcs7) {
        this.pcs7 = pcs7;
    }

    public BigDecimal getPcs8() {
        return this.pcs8;
    }

    public void setPcs8(BigDecimal pcs8) {
        this.pcs8 = pcs8;
    }

    public BigDecimal getPcs9() {
        return this.pcs9;
    }

    public void setPcs9(BigDecimal pcs9) {
        this.pcs9 = pcs9;
    }

    public BigDecimal getPcs10() {
        return this.pcs10;
    }

    public void setPcs10(BigDecimal pcs10) {
        this.pcs10 = pcs10;
    }

    public BigDecimal getPcs11() {
        return this.pcs11;
    }

    public void setPcs11(BigDecimal pcs11) {
        this.pcs11 = pcs11;
    }

    public BigDecimal getPcs12() {
        return this.pcs12;
    }

    public void setPcs12(BigDecimal pcs12) {
        this.pcs12 = pcs12;
    }

    public BigDecimal getPcs13() {
        return this.pcs13;
    }

    public void setPcs13(BigDecimal pcs13) {
        this.pcs13 = pcs13;
    }

    public BigDecimal getPcs14() {
        return this.pcs14;
    }

    public void setPcs14(BigDecimal pcs14) {
        this.pcs14 = pcs14;
    }

    public BigDecimal getPcs15() {
        return this.pcs15;
    }

    public void setPcs15(BigDecimal pcs15) {
        this.pcs15 = pcs15;
    }

    public BigDecimal getPcs16() {
        return this.pcs16;
    }

    public void setPcs16(BigDecimal pcs16) {
        this.pcs16 = pcs16;
    }

    public BigInteger getWtotalTotpcs() {
        return this.wtotalTotpcs;
    }

    public void setWtotalTotpcs(BigInteger wtotalTotpcs) {
        this.wtotalTotpcs = wtotalTotpcs;
    }

    public BigInteger getWtotalBal() {
        return this.wtotalBal;
    }

    public void setWtotalBal(BigInteger wtotalBal) {
        this.wtotalBal = wtotalBal;
    }

    public BigDecimal getWtotalComp() {
        return this.wtotalComp;
    }

    public void setWtotalComp(BigDecimal wtotalComp) {
        this.wtotalComp = wtotalComp;
    }

    public BigInteger getTotpcs1() {
        return this.totpcs1;
    }

    public void setTotpcs1(BigInteger totpcs1) {
        this.totpcs1 = totpcs1;
    }

    public BigInteger getTotpcs2() {
        return this.totpcs2;
    }

    public void setTotpcs2(BigInteger totpcs2) {
        this.totpcs2 = totpcs2;
    }

    public BigInteger getTotpcs3() {
        return this.totpcs3;
    }

    public void setTotpcs3(BigInteger totpcs3) {
        this.totpcs3 = totpcs3;
    }

    public BigInteger getTotpcs4() {
        return this.totpcs4;
    }

    public void setTotpcs4(BigInteger totpcs4) {
        this.totpcs4 = totpcs4;
    }

    public BigInteger getTotpcs5() {
        return this.totpcs5;
    }

    public void setTotpcs5(BigInteger totpcs5) {
        this.totpcs5 = totpcs5;
    }

    public BigInteger getTotpcs6() {
        return this.totpcs6;
    }

    public void setTotpcs6(BigInteger totpcs6) {
        this.totpcs6 = totpcs6;
    }

    public BigInteger getTotpcs7() {
        return this.totpcs7;
    }

    public void setTotpcs7(BigInteger totpcs7) {
        this.totpcs7 = totpcs7;
    }

    public BigInteger getTotpcs8() {
        return this.totpcs8;
    }

    public void setTotpcs8(BigInteger totpcs8) {
        this.totpcs8 = totpcs8;
    }

    public BigInteger getTotpcs9() {
        return this.totpcs9;
    }

    public void setTotpcs9(BigInteger totpcs9) {
        this.totpcs9 = totpcs9;
    }

    public BigInteger getTotpcs10() {
        return this.totpcs10;
    }

    public void setTotpcs10(BigInteger totpcs10) {
        this.totpcs10 = totpcs10;
    }

    public BigInteger getTotpcs11() {
        return this.totpcs11;
    }

    public void setTotpcs11(BigInteger totpcs11) {
        this.totpcs11 = totpcs11;
    }

    public BigInteger getTotpcs12() {
        return this.totpcs12;
    }

    public void setTotpcs12(BigInteger totpcs12) {
        this.totpcs12 = totpcs12;
    }

    public BigInteger getTotpcs13() {
        return this.totpcs13;
    }

    public void setTotpcs13(BigInteger totpcs13) {
        this.totpcs13 = totpcs13;
    }

    public BigInteger getTotpcs14() {
        return this.totpcs14;
    }

    public void setTotpcs14(BigInteger totpcs14) {
        this.totpcs14 = totpcs14;
    }

    public BigInteger getTotpcs15() {
        return this.totpcs15;
    }

    public void setTotpcs15(BigInteger totpcs15) {
        this.totpcs15 = totpcs15;
    }

    public BigInteger getTotpcs16() {
        return this.totpcs16;
    }

    public void setTotpcs16(BigInteger totpcs16) {
        this.totpcs16 = totpcs16;
    }

    public BigInteger getBal1() {
        return this.bal1;
    }

    public void setBal1(BigInteger bal1) {
        this.bal1 = bal1;
    }

    public BigInteger getBal2() {
        return this.bal2;
    }

    public void setBal2(BigInteger bal2) {
        this.bal2 = bal2;
    }

    public BigInteger getBal3() {
        return this.bal3;
    }

    public void setBal3(BigInteger bal3) {
        this.bal3 = bal3;
    }

    public BigInteger getBal4() {
        return this.bal4;
    }

    public void setBal4(BigInteger bal4) {
        this.bal4 = bal4;
    }

    public BigInteger getBal5() {
        return this.bal5;
    }

    public void setBal5(BigInteger bal5) {
        this.bal5 = bal5;
    }

    public BigInteger getBal6() {
        return this.bal6;
    }

    public void setBal6(BigInteger bal6) {
        this.bal6 = bal6;
    }

    public BigInteger getBal7() {
        return this.bal7;
    }

    public void setBal7(BigInteger bal7) {
        this.bal7 = bal7;
    }

    public BigInteger getBal8() {
        return this.bal8;
    }

    public void setBal8(BigInteger bal8) {
        this.bal8 = bal8;
    }

    public BigInteger getBal9() {
        return this.bal9;
    }

    public void setBal9(BigInteger bal9) {
        this.bal9 = bal9;
    }

    public BigInteger getBal10() {
        return this.bal10;
    }

    public void setBal10(BigInteger bal10) {
        this.bal10 = bal10;
    }

    public BigInteger getBal11() {
        return this.bal11;
    }

    public void setBal11(BigInteger bal11) {
        this.bal11 = bal11;
    }

    public BigInteger getBal12() {
        return this.bal12;
    }

    public void setBal12(BigInteger bal12) {
        this.bal12 = bal12;
    }

    public BigInteger getBal13() {
        return this.bal13;
    }

    public void setBal13(BigInteger bal13) {
        this.bal13 = bal13;
    }

    public BigInteger getBal14() {
        return this.bal14;
    }

    public void setBal14(BigInteger bal14) {
        this.bal14 = bal14;
    }

    public BigInteger getBal15() {
        return this.bal15;
    }

    public void setBal15(BigInteger bal15) {
        this.bal15 = bal15;
    }

    public BigInteger getBal16() {
        return this.bal16;
    }

    public void setBal16(BigInteger bal16) {
        this.bal16 = bal16;
    }

    public BigDecimal getComp1() {
        return this.comp1;
    }

    public void setComp1(BigDecimal comp1) {
        this.comp1 = comp1;
    }

    public BigDecimal getComp2() {
        return this.comp2;
    }

    public void setComp2(BigDecimal comp2) {
        this.comp2 = comp2;
    }

    public BigDecimal getComp3() {
        return this.comp3;
    }

    public void setComp3(BigDecimal comp3) {
        this.comp3 = comp3;
    }

    public BigDecimal getComp4() {
        return this.comp4;
    }

    public void setComp4(BigDecimal comp4) {
        this.comp4 = comp4;
    }

    public BigDecimal getComp5() {
        return this.comp5;
    }

    public void setComp5(BigDecimal comp5) {
        this.comp5 = comp5;
    }

    public BigDecimal getComp6() {
        return this.comp6;
    }

    public void setComp6(BigDecimal comp6) {
        this.comp6 = comp6;
    }

    public BigDecimal getComp7() {
        return this.comp7;
    }

    public void setComp7(BigDecimal comp7) {
        this.comp7 = comp7;
    }

    public BigDecimal getComp8() {
        return this.comp8;
    }

    public void setComp8(BigDecimal comp8) {
        this.comp8 = comp8;
    }

    public BigDecimal getComp9() {
        return this.comp9;
    }

    public void setComp9(BigDecimal comp9) {
        this.comp9 = comp9;
    }

    public BigDecimal getComp10() {
        return this.comp10;
    }

    public void setComp10(BigDecimal comp10) {
        this.comp10 = comp10;
    }

    public BigDecimal getComp11() {
        return this.comp11;
    }

    public void setComp11(BigDecimal comp11) {
        this.comp11 = comp11;
    }

    public BigDecimal getComp12() {
        return this.comp12;
    }

    public void setComp12(BigDecimal comp12) {
        this.comp12 = comp12;
    }

    public BigDecimal getComp13() {
        return this.comp13;
    }

    public void setComp13(BigDecimal comp13) {
        this.comp13 = comp13;
    }

    public BigDecimal getComp14() {
        return this.comp14;
    }

    public void setComp14(BigDecimal comp14) {
        this.comp14 = comp14;
    }

    public BigDecimal getComp15() {
        return this.comp15;
    }

    public void setComp15(BigDecimal comp15) {
        this.comp15 = comp15;
    }

    public BigDecimal getComp16() {
        return this.comp16;
    }

    public void setComp16(BigDecimal comp16) {
        this.comp16 = comp16;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0Cr600pcsCartonedResponsePoutPshpList)) return false;
        final ProcCr1100pk0Cr600pcsCartonedResponsePoutPshpList procCr1100pk0cr600pcsCartonedResponsePoutPshpList = (ProcCr1100pk0Cr600pcsCartonedResponsePoutPshpList) o;
        return Objects.equals(getShpnum(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getShpnum()) &&
                Objects.equals(getPshpnum(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPshpnum()) &&
                Objects.equals(getSection(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getSection()) &&
                Objects.equals(getScandat(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getScandat()) &&
                Objects.equals(getUnit(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getUnit()) &&
                Objects.equals(getCtns(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getCtns()) &&
                Objects.equals(getOrdnum(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getOrdnum()) &&
                Objects.equals(getGmtseq(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getGmtseq()) &&
                Objects.equals(getClrseq(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getClrseq()) &&
                Objects.equals(getTrncode(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTrncode()) &&
                Objects.equals(getStatus(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getStatus()) &&
                Objects.equals(getWdelivdat(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getWdelivdat()) &&
                Objects.equals(getQtyord1(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord1()) &&
                Objects.equals(getQtyord2(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord2()) &&
                Objects.equals(getQtyord3(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord3()) &&
                Objects.equals(getQtyord4(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord4()) &&
                Objects.equals(getQtyord5(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord5()) &&
                Objects.equals(getQtyord6(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord6()) &&
                Objects.equals(getQtyord7(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord7()) &&
                Objects.equals(getQtyord8(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord8()) &&
                Objects.equals(getQtyord9(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord9()) &&
                Objects.equals(getQtyord10(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord10()) &&
                Objects.equals(getQtyord11(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord11()) &&
                Objects.equals(getQtyord12(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord12()) &&
                Objects.equals(getQtyord13(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord13()) &&
                Objects.equals(getQtyord14(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord14()) &&
                Objects.equals(getQtyord15(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord15()) &&
                Objects.equals(getQtyord16(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getQtyord16()) &&
                Objects.equals(getWtotalQtyord(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getWtotalQtyord()) &&
                Objects.equals(getTotpcs(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs()) &&
                Objects.equals(getPcs1(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs1()) &&
                Objects.equals(getPcs2(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs2()) &&
                Objects.equals(getPcs3(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs3()) &&
                Objects.equals(getPcs4(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs4()) &&
                Objects.equals(getPcs5(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs5()) &&
                Objects.equals(getPcs6(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs6()) &&
                Objects.equals(getPcs7(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs7()) &&
                Objects.equals(getPcs8(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs8()) &&
                Objects.equals(getPcs9(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs9()) &&
                Objects.equals(getPcs10(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs10()) &&
                Objects.equals(getPcs11(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs11()) &&
                Objects.equals(getPcs12(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs12()) &&
                Objects.equals(getPcs13(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs13()) &&
                Objects.equals(getPcs14(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs14()) &&
                Objects.equals(getPcs15(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs15()) &&
                Objects.equals(getPcs16(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getPcs16()) &&
                Objects.equals(getWtotalTotpcs(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getWtotalTotpcs()) &&
                Objects.equals(getWtotalBal(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getWtotalBal()) &&
                Objects.equals(getWtotalComp(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getWtotalComp()) &&
                Objects.equals(getTotpcs1(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs1()) &&
                Objects.equals(getTotpcs2(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs2()) &&
                Objects.equals(getTotpcs3(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs3()) &&
                Objects.equals(getTotpcs4(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs4()) &&
                Objects.equals(getTotpcs5(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs5()) &&
                Objects.equals(getTotpcs6(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs6()) &&
                Objects.equals(getTotpcs7(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs7()) &&
                Objects.equals(getTotpcs8(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs8()) &&
                Objects.equals(getTotpcs9(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs9()) &&
                Objects.equals(getTotpcs10(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs10()) &&
                Objects.equals(getTotpcs11(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs11()) &&
                Objects.equals(getTotpcs12(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs12()) &&
                Objects.equals(getTotpcs13(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs13()) &&
                Objects.equals(getTotpcs14(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs14()) &&
                Objects.equals(getTotpcs15(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs15()) &&
                Objects.equals(getTotpcs16(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getTotpcs16()) &&
                Objects.equals(getBal1(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal1()) &&
                Objects.equals(getBal2(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal2()) &&
                Objects.equals(getBal3(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal3()) &&
                Objects.equals(getBal4(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal4()) &&
                Objects.equals(getBal5(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal5()) &&
                Objects.equals(getBal6(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal6()) &&
                Objects.equals(getBal7(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal7()) &&
                Objects.equals(getBal8(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal8()) &&
                Objects.equals(getBal9(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal9()) &&
                Objects.equals(getBal10(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal10()) &&
                Objects.equals(getBal11(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal11()) &&
                Objects.equals(getBal12(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal12()) &&
                Objects.equals(getBal13(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal13()) &&
                Objects.equals(getBal14(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal14()) &&
                Objects.equals(getBal15(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal15()) &&
                Objects.equals(getBal16(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getBal16()) &&
                Objects.equals(getComp1(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp1()) &&
                Objects.equals(getComp2(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp2()) &&
                Objects.equals(getComp3(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp3()) &&
                Objects.equals(getComp4(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp4()) &&
                Objects.equals(getComp5(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp5()) &&
                Objects.equals(getComp6(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp6()) &&
                Objects.equals(getComp7(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp7()) &&
                Objects.equals(getComp8(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp8()) &&
                Objects.equals(getComp9(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp9()) &&
                Objects.equals(getComp10(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp10()) &&
                Objects.equals(getComp11(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp11()) &&
                Objects.equals(getComp12(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp12()) &&
                Objects.equals(getComp13(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp13()) &&
                Objects.equals(getComp14(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp14()) &&
                Objects.equals(getComp15(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp15()) &&
                Objects.equals(getComp16(), procCr1100pk0cr600pcsCartonedResponsePoutPshpList.getComp16());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShpnum(),
                getPshpnum(),
                getSection(),
                getScandat(),
                getUnit(),
                getCtns(),
                getOrdnum(),
                getGmtseq(),
                getClrseq(),
                getTrncode(),
                getStatus(),
                getWdelivdat(),
                getQtyord1(),
                getQtyord2(),
                getQtyord3(),
                getQtyord4(),
                getQtyord5(),
                getQtyord6(),
                getQtyord7(),
                getQtyord8(),
                getQtyord9(),
                getQtyord10(),
                getQtyord11(),
                getQtyord12(),
                getQtyord13(),
                getQtyord14(),
                getQtyord15(),
                getQtyord16(),
                getWtotalQtyord(),
                getTotpcs(),
                getPcs1(),
                getPcs2(),
                getPcs3(),
                getPcs4(),
                getPcs5(),
                getPcs6(),
                getPcs7(),
                getPcs8(),
                getPcs9(),
                getPcs10(),
                getPcs11(),
                getPcs12(),
                getPcs13(),
                getPcs14(),
                getPcs15(),
                getPcs16(),
                getWtotalTotpcs(),
                getWtotalBal(),
                getWtotalComp(),
                getTotpcs1(),
                getTotpcs2(),
                getTotpcs3(),
                getTotpcs4(),
                getTotpcs5(),
                getTotpcs6(),
                getTotpcs7(),
                getTotpcs8(),
                getTotpcs9(),
                getTotpcs10(),
                getTotpcs11(),
                getTotpcs12(),
                getTotpcs13(),
                getTotpcs14(),
                getTotpcs15(),
                getTotpcs16(),
                getBal1(),
                getBal2(),
                getBal3(),
                getBal4(),
                getBal5(),
                getBal6(),
                getBal7(),
                getBal8(),
                getBal9(),
                getBal10(),
                getBal11(),
                getBal12(),
                getBal13(),
                getBal14(),
                getBal15(),
                getBal16(),
                getComp1(),
                getComp2(),
                getComp3(),
                getComp4(),
                getComp5(),
                getComp6(),
                getComp7(),
                getComp8(),
                getComp9(),
                getComp10(),
                getComp11(),
                getComp12(),
                getComp13(),
                getComp14(),
                getComp15(),
                getComp16());
    }
}