/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0GetCr210orderDetResponse implements Serializable {


    @ColumnAlias("poutOrderDet")
    private List<ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet> poutOrderDet;

    public List<ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet> getPoutOrderDet() {
        return this.poutOrderDet;
    }

    public void setPoutOrderDet(List<ProcCr1100pk0GetCr210orderDetResponsePoutOrderDet> poutOrderDet) {
        this.poutOrderDet = poutOrderDet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0GetCr210orderDetResponse)) return false;
        final ProcCr1100pk0GetCr210orderDetResponse procCr1100pk0getCr210orderDetResponse = (ProcCr1100pk0GetCr210orderDetResponse) o;
        return Objects.equals(getPoutOrderDet(), procCr1100pk0getCr210orderDetResponse.getPoutOrderDet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutOrderDet());
    }
}