/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0Cr210pShpDetResponsePoutpShpDet implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("PSHPNUM")
    private String pshpnum;

    @ColumnAlias("PSHPMOD")
    private String pshpmod;

    @ColumnAlias("PSHPDST")
    private String pshpdst;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("FINLCN")
    private String finlcn;

    @ColumnAlias("FINDAT")
    private LocalDateTime findat;

    @ColumnAlias("DELDAT")
    private LocalDateTime deldat;

    @ColumnAlias("W_CTNS")
    private BigInteger wctns;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public String getPshpmod() {
        return this.pshpmod;
    }

    public void setPshpmod(String pshpmod) {
        this.pshpmod = pshpmod;
    }

    public String getPshpdst() {
        return this.pshpdst;
    }

    public void setPshpdst(String pshpdst) {
        this.pshpdst = pshpdst;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getFinlcn() {
        return this.finlcn;
    }

    public void setFinlcn(String finlcn) {
        this.finlcn = finlcn;
    }

    public LocalDateTime getFindat() {
        return this.findat;
    }

    public void setFindat(LocalDateTime findat) {
        this.findat = findat;
    }

    public LocalDateTime getDeldat() {
        return this.deldat;
    }

    public void setDeldat(LocalDateTime deldat) {
        this.deldat = deldat;
    }

    public BigInteger getWctns() {
        return this.wctns;
    }

    public void setWctns(BigInteger wctns) {
        this.wctns = wctns;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0Cr210pShpDetResponsePoutpShpDet)) return false;
        final ProcCr1100pk0Cr210pShpDetResponsePoutpShpDet procCr1100pk0cr210pShpDetResponsePoutpShpDet = (ProcCr1100pk0Cr210pShpDetResponsePoutpShpDet) o;
        return Objects.equals(getOrdnum(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getOrdnum()) &&
                Objects.equals(getShpnum(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getShpnum()) &&
                Objects.equals(getPshpnum(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getPshpnum()) &&
                Objects.equals(getPshpmod(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getPshpmod()) &&
                Objects.equals(getPshpdst(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getPshpdst()) &&
                Objects.equals(getStatus(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getStatus()) &&
                Objects.equals(getFinlcn(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getFinlcn()) &&
                Objects.equals(getFindat(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getFindat()) &&
                Objects.equals(getDeldat(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getDeldat()) &&
                Objects.equals(getWctns(), procCr1100pk0cr210pShpDetResponsePoutpShpDet.getWctns());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getShpnum(),
                getPshpnum(),
                getPshpmod(),
                getPshpdst(),
                getStatus(),
                getFinlcn(),
                getFindat(),
                getDeldat(),
                getWctns());
    }
}