/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr800pk0ProvpklCartonDefResponse implements Serializable {


    @ColumnAlias("poutCtntype")
    private List<ProcCr800pk0ProvpklCartonDefResponsePoutCtntype> poutCtntype;

    public List<ProcCr800pk0ProvpklCartonDefResponsePoutCtntype> getPoutCtntype() {
        return this.poutCtntype;
    }

    public void setPoutCtntype(List<ProcCr800pk0ProvpklCartonDefResponsePoutCtntype> poutCtntype) {
        this.poutCtntype = poutCtntype;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr800pk0ProvpklCartonDefResponse)) return false;
        final ProcCr800pk0ProvpklCartonDefResponse procCr800pk0provpklCartonDefResponse = (ProcCr800pk0ProvpklCartonDefResponse) o;
        return Objects.equals(getPoutCtntype(), procCr800pk0provpklCartonDefResponse.getPoutCtntype());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCtntype());
    }
}