/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0Cr610pklQtyResponsePoutPacks implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("PSHPNUM")
    private String pshpnum;

    @ColumnAlias("SEQCOD")
    private String seqcod;

    @ColumnAlias("WPCKDES")
    private String wpckdes;

    @ColumnAlias("WCTNQTY1")
    private BigDecimal wctnqty1;

    @ColumnAlias("WCTNQTY2")
    private BigDecimal wctnqty2;

    @ColumnAlias("WCTNQTY3")
    private BigDecimal wctnqty3;

    @ColumnAlias("WCTNQTY4")
    private BigDecimal wctnqty4;

    @ColumnAlias("WCTNQTY5")
    private BigDecimal wctnqty5;

    @ColumnAlias("WCTNQTY6")
    private BigDecimal wctnqty6;

    @ColumnAlias("WCTNQTY7")
    private BigDecimal wctnqty7;

    @ColumnAlias("WCTNQTY8")
    private BigDecimal wctnqty8;

    @ColumnAlias("WCTNQTY9")
    private BigDecimal wctnqty9;

    @ColumnAlias("WCTNQTY10")
    private BigDecimal wctnqty10;

    @ColumnAlias("WCTNQTY11")
    private BigDecimal wctnqty11;

    @ColumnAlias("WCTNQTY12")
    private BigDecimal wctnqty12;

    @ColumnAlias("WCTNQTY13")
    private BigDecimal wctnqty13;

    @ColumnAlias("WCTNQTY14")
    private BigDecimal wctnqty14;

    @ColumnAlias("WCTNQTY15")
    private BigDecimal wctnqty15;

    @ColumnAlias("WCTNQTY16")
    private BigDecimal wctnqty16;

    @ColumnAlias("WQTYORD1")
    private BigDecimal wqtyord1;

    @ColumnAlias("WQTYORD2")
    private BigDecimal wqtyord2;

    @ColumnAlias("WQTYORD3")
    private BigDecimal wqtyord3;

    @ColumnAlias("WQTYORD4")
    private BigDecimal wqtyord4;

    @ColumnAlias("WQTYORD5")
    private BigDecimal wqtyord5;

    @ColumnAlias("WQTYORD6")
    private BigDecimal wqtyord6;

    @ColumnAlias("WQTYORD7")
    private BigDecimal wqtyord7;

    @ColumnAlias("WQTYORD8")
    private BigDecimal wqtyord8;

    @ColumnAlias("WQTYORD9")
    private BigDecimal wqtyord9;

    @ColumnAlias("WQTYORD10")
    private BigDecimal wqtyord10;

    @ColumnAlias("WQTYORD11")
    private BigDecimal wqtyord11;

    @ColumnAlias("WQTYORD12")
    private BigDecimal wqtyord12;

    @ColumnAlias("WQTYORD13")
    private BigDecimal wqtyord13;

    @ColumnAlias("WQTYORD14")
    private BigDecimal wqtyord14;

    @ColumnAlias("WQTYORD15")
    private BigDecimal wqtyord15;

    @ColumnAlias("WQTYORD16")
    private BigDecimal wqtyord16;

    @ColumnAlias("WBAL1")
    private BigInteger wbal1;

    @ColumnAlias("WBAL2")
    private BigInteger wbal2;

    @ColumnAlias("WBAL3")
    private BigInteger wbal3;

    @ColumnAlias("WBAL4")
    private BigInteger wbal4;

    @ColumnAlias("WBAL5")
    private BigInteger wbal5;

    @ColumnAlias("WBAL6")
    private BigInteger wbal6;

    @ColumnAlias("WBAL7")
    private BigInteger wbal7;

    @ColumnAlias("WBAL8")
    private BigInteger wbal8;

    @ColumnAlias("WBAL9")
    private BigInteger wbal9;

    @ColumnAlias("WBAL10")
    private BigInteger wbal10;

    @ColumnAlias("WBAL11")
    private BigInteger wbal11;

    @ColumnAlias("WBAL12")
    private BigInteger wbal12;

    @ColumnAlias("WBAL13")
    private BigInteger wbal13;

    @ColumnAlias("WBAL14")
    private BigInteger wbal14;

    @ColumnAlias("WBAL15")
    private BigInteger wbal15;

    @ColumnAlias("WBAL16")
    private BigInteger wbal16;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public String getSeqcod() {
        return this.seqcod;
    }

    public void setSeqcod(String seqcod) {
        this.seqcod = seqcod;
    }

    public String getWpckdes() {
        return this.wpckdes;
    }

    public void setWpckdes(String wpckdes) {
        this.wpckdes = wpckdes;
    }

    public BigDecimal getWctnqty1() {
        return this.wctnqty1;
    }

    public void setWctnqty1(BigDecimal wctnqty1) {
        this.wctnqty1 = wctnqty1;
    }

    public BigDecimal getWctnqty2() {
        return this.wctnqty2;
    }

    public void setWctnqty2(BigDecimal wctnqty2) {
        this.wctnqty2 = wctnqty2;
    }

    public BigDecimal getWctnqty3() {
        return this.wctnqty3;
    }

    public void setWctnqty3(BigDecimal wctnqty3) {
        this.wctnqty3 = wctnqty3;
    }

    public BigDecimal getWctnqty4() {
        return this.wctnqty4;
    }

    public void setWctnqty4(BigDecimal wctnqty4) {
        this.wctnqty4 = wctnqty4;
    }

    public BigDecimal getWctnqty5() {
        return this.wctnqty5;
    }

    public void setWctnqty5(BigDecimal wctnqty5) {
        this.wctnqty5 = wctnqty5;
    }

    public BigDecimal getWctnqty6() {
        return this.wctnqty6;
    }

    public void setWctnqty6(BigDecimal wctnqty6) {
        this.wctnqty6 = wctnqty6;
    }

    public BigDecimal getWctnqty7() {
        return this.wctnqty7;
    }

    public void setWctnqty7(BigDecimal wctnqty7) {
        this.wctnqty7 = wctnqty7;
    }

    public BigDecimal getWctnqty8() {
        return this.wctnqty8;
    }

    public void setWctnqty8(BigDecimal wctnqty8) {
        this.wctnqty8 = wctnqty8;
    }

    public BigDecimal getWctnqty9() {
        return this.wctnqty9;
    }

    public void setWctnqty9(BigDecimal wctnqty9) {
        this.wctnqty9 = wctnqty9;
    }

    public BigDecimal getWctnqty10() {
        return this.wctnqty10;
    }

    public void setWctnqty10(BigDecimal wctnqty10) {
        this.wctnqty10 = wctnqty10;
    }

    public BigDecimal getWctnqty11() {
        return this.wctnqty11;
    }

    public void setWctnqty11(BigDecimal wctnqty11) {
        this.wctnqty11 = wctnqty11;
    }

    public BigDecimal getWctnqty12() {
        return this.wctnqty12;
    }

    public void setWctnqty12(BigDecimal wctnqty12) {
        this.wctnqty12 = wctnqty12;
    }

    public BigDecimal getWctnqty13() {
        return this.wctnqty13;
    }

    public void setWctnqty13(BigDecimal wctnqty13) {
        this.wctnqty13 = wctnqty13;
    }

    public BigDecimal getWctnqty14() {
        return this.wctnqty14;
    }

    public void setWctnqty14(BigDecimal wctnqty14) {
        this.wctnqty14 = wctnqty14;
    }

    public BigDecimal getWctnqty15() {
        return this.wctnqty15;
    }

    public void setWctnqty15(BigDecimal wctnqty15) {
        this.wctnqty15 = wctnqty15;
    }

    public BigDecimal getWctnqty16() {
        return this.wctnqty16;
    }

    public void setWctnqty16(BigDecimal wctnqty16) {
        this.wctnqty16 = wctnqty16;
    }

    public BigDecimal getWqtyord1() {
        return this.wqtyord1;
    }

    public void setWqtyord1(BigDecimal wqtyord1) {
        this.wqtyord1 = wqtyord1;
    }

    public BigDecimal getWqtyord2() {
        return this.wqtyord2;
    }

    public void setWqtyord2(BigDecimal wqtyord2) {
        this.wqtyord2 = wqtyord2;
    }

    public BigDecimal getWqtyord3() {
        return this.wqtyord3;
    }

    public void setWqtyord3(BigDecimal wqtyord3) {
        this.wqtyord3 = wqtyord3;
    }

    public BigDecimal getWqtyord4() {
        return this.wqtyord4;
    }

    public void setWqtyord4(BigDecimal wqtyord4) {
        this.wqtyord4 = wqtyord4;
    }

    public BigDecimal getWqtyord5() {
        return this.wqtyord5;
    }

    public void setWqtyord5(BigDecimal wqtyord5) {
        this.wqtyord5 = wqtyord5;
    }

    public BigDecimal getWqtyord6() {
        return this.wqtyord6;
    }

    public void setWqtyord6(BigDecimal wqtyord6) {
        this.wqtyord6 = wqtyord6;
    }

    public BigDecimal getWqtyord7() {
        return this.wqtyord7;
    }

    public void setWqtyord7(BigDecimal wqtyord7) {
        this.wqtyord7 = wqtyord7;
    }

    public BigDecimal getWqtyord8() {
        return this.wqtyord8;
    }

    public void setWqtyord8(BigDecimal wqtyord8) {
        this.wqtyord8 = wqtyord8;
    }

    public BigDecimal getWqtyord9() {
        return this.wqtyord9;
    }

    public void setWqtyord9(BigDecimal wqtyord9) {
        this.wqtyord9 = wqtyord9;
    }

    public BigDecimal getWqtyord10() {
        return this.wqtyord10;
    }

    public void setWqtyord10(BigDecimal wqtyord10) {
        this.wqtyord10 = wqtyord10;
    }

    public BigDecimal getWqtyord11() {
        return this.wqtyord11;
    }

    public void setWqtyord11(BigDecimal wqtyord11) {
        this.wqtyord11 = wqtyord11;
    }

    public BigDecimal getWqtyord12() {
        return this.wqtyord12;
    }

    public void setWqtyord12(BigDecimal wqtyord12) {
        this.wqtyord12 = wqtyord12;
    }

    public BigDecimal getWqtyord13() {
        return this.wqtyord13;
    }

    public void setWqtyord13(BigDecimal wqtyord13) {
        this.wqtyord13 = wqtyord13;
    }

    public BigDecimal getWqtyord14() {
        return this.wqtyord14;
    }

    public void setWqtyord14(BigDecimal wqtyord14) {
        this.wqtyord14 = wqtyord14;
    }

    public BigDecimal getWqtyord15() {
        return this.wqtyord15;
    }

    public void setWqtyord15(BigDecimal wqtyord15) {
        this.wqtyord15 = wqtyord15;
    }

    public BigDecimal getWqtyord16() {
        return this.wqtyord16;
    }

    public void setWqtyord16(BigDecimal wqtyord16) {
        this.wqtyord16 = wqtyord16;
    }

    public BigInteger getWbal1() {
        return this.wbal1;
    }

    public void setWbal1(BigInteger wbal1) {
        this.wbal1 = wbal1;
    }

    public BigInteger getWbal2() {
        return this.wbal2;
    }

    public void setWbal2(BigInteger wbal2) {
        this.wbal2 = wbal2;
    }

    public BigInteger getWbal3() {
        return this.wbal3;
    }

    public void setWbal3(BigInteger wbal3) {
        this.wbal3 = wbal3;
    }

    public BigInteger getWbal4() {
        return this.wbal4;
    }

    public void setWbal4(BigInteger wbal4) {
        this.wbal4 = wbal4;
    }

    public BigInteger getWbal5() {
        return this.wbal5;
    }

    public void setWbal5(BigInteger wbal5) {
        this.wbal5 = wbal5;
    }

    public BigInteger getWbal6() {
        return this.wbal6;
    }

    public void setWbal6(BigInteger wbal6) {
        this.wbal6 = wbal6;
    }

    public BigInteger getWbal7() {
        return this.wbal7;
    }

    public void setWbal7(BigInteger wbal7) {
        this.wbal7 = wbal7;
    }

    public BigInteger getWbal8() {
        return this.wbal8;
    }

    public void setWbal8(BigInteger wbal8) {
        this.wbal8 = wbal8;
    }

    public BigInteger getWbal9() {
        return this.wbal9;
    }

    public void setWbal9(BigInteger wbal9) {
        this.wbal9 = wbal9;
    }

    public BigInteger getWbal10() {
        return this.wbal10;
    }

    public void setWbal10(BigInteger wbal10) {
        this.wbal10 = wbal10;
    }

    public BigInteger getWbal11() {
        return this.wbal11;
    }

    public void setWbal11(BigInteger wbal11) {
        this.wbal11 = wbal11;
    }

    public BigInteger getWbal12() {
        return this.wbal12;
    }

    public void setWbal12(BigInteger wbal12) {
        this.wbal12 = wbal12;
    }

    public BigInteger getWbal13() {
        return this.wbal13;
    }

    public void setWbal13(BigInteger wbal13) {
        this.wbal13 = wbal13;
    }

    public BigInteger getWbal14() {
        return this.wbal14;
    }

    public void setWbal14(BigInteger wbal14) {
        this.wbal14 = wbal14;
    }

    public BigInteger getWbal15() {
        return this.wbal15;
    }

    public void setWbal15(BigInteger wbal15) {
        this.wbal15 = wbal15;
    }

    public BigInteger getWbal16() {
        return this.wbal16;
    }

    public void setWbal16(BigInteger wbal16) {
        this.wbal16 = wbal16;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0Cr610pklQtyResponsePoutPacks)) return false;
        final ProcCr1100pk0Cr610pklQtyResponsePoutPacks procCr1100pk0cr610pklQtyResponsePoutPacks = (ProcCr1100pk0Cr610pklQtyResponsePoutPacks) o;
        return Objects.equals(getOrdnum(), procCr1100pk0cr610pklQtyResponsePoutPacks.getOrdnum()) &&
                Objects.equals(getShpnum(), procCr1100pk0cr610pklQtyResponsePoutPacks.getShpnum()) &&
                Objects.equals(getPshpnum(), procCr1100pk0cr610pklQtyResponsePoutPacks.getPshpnum()) &&
                Objects.equals(getSeqcod(), procCr1100pk0cr610pklQtyResponsePoutPacks.getSeqcod()) &&
                Objects.equals(getWpckdes(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWpckdes()) &&
                Objects.equals(getWctnqty1(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty1()) &&
                Objects.equals(getWctnqty2(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty2()) &&
                Objects.equals(getWctnqty3(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty3()) &&
                Objects.equals(getWctnqty4(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty4()) &&
                Objects.equals(getWctnqty5(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty5()) &&
                Objects.equals(getWctnqty6(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty6()) &&
                Objects.equals(getWctnqty7(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty7()) &&
                Objects.equals(getWctnqty8(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty8()) &&
                Objects.equals(getWctnqty9(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty9()) &&
                Objects.equals(getWctnqty10(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty10()) &&
                Objects.equals(getWctnqty11(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty11()) &&
                Objects.equals(getWctnqty12(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty12()) &&
                Objects.equals(getWctnqty13(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty13()) &&
                Objects.equals(getWctnqty14(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty14()) &&
                Objects.equals(getWctnqty15(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty15()) &&
                Objects.equals(getWctnqty16(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWctnqty16()) &&
                Objects.equals(getWqtyord1(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord1()) &&
                Objects.equals(getWqtyord2(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord2()) &&
                Objects.equals(getWqtyord3(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord3()) &&
                Objects.equals(getWqtyord4(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord4()) &&
                Objects.equals(getWqtyord5(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord5()) &&
                Objects.equals(getWqtyord6(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord6()) &&
                Objects.equals(getWqtyord7(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord7()) &&
                Objects.equals(getWqtyord8(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord8()) &&
                Objects.equals(getWqtyord9(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord9()) &&
                Objects.equals(getWqtyord10(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord10()) &&
                Objects.equals(getWqtyord11(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord11()) &&
                Objects.equals(getWqtyord12(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord12()) &&
                Objects.equals(getWqtyord13(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord13()) &&
                Objects.equals(getWqtyord14(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord14()) &&
                Objects.equals(getWqtyord15(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord15()) &&
                Objects.equals(getWqtyord16(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWqtyord16()) &&
                Objects.equals(getWbal1(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal1()) &&
                Objects.equals(getWbal2(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal2()) &&
                Objects.equals(getWbal3(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal3()) &&
                Objects.equals(getWbal4(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal4()) &&
                Objects.equals(getWbal5(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal5()) &&
                Objects.equals(getWbal6(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal6()) &&
                Objects.equals(getWbal7(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal7()) &&
                Objects.equals(getWbal8(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal8()) &&
                Objects.equals(getWbal9(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal9()) &&
                Objects.equals(getWbal10(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal10()) &&
                Objects.equals(getWbal11(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal11()) &&
                Objects.equals(getWbal12(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal12()) &&
                Objects.equals(getWbal13(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal13()) &&
                Objects.equals(getWbal14(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal14()) &&
                Objects.equals(getWbal15(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal15()) &&
                Objects.equals(getWbal16(), procCr1100pk0cr610pklQtyResponsePoutPacks.getWbal16());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getShpnum(),
                getPshpnum(),
                getSeqcod(),
                getWpckdes(),
                getWctnqty1(),
                getWctnqty2(),
                getWctnqty3(),
                getWctnqty4(),
                getWctnqty5(),
                getWctnqty6(),
                getWctnqty7(),
                getWctnqty8(),
                getWctnqty9(),
                getWctnqty10(),
                getWctnqty11(),
                getWctnqty12(),
                getWctnqty13(),
                getWctnqty14(),
                getWctnqty15(),
                getWctnqty16(),
                getWqtyord1(),
                getWqtyord2(),
                getWqtyord3(),
                getWqtyord4(),
                getWqtyord5(),
                getWqtyord6(),
                getWqtyord7(),
                getWqtyord8(),
                getWqtyord9(),
                getWqtyord10(),
                getWqtyord11(),
                getWqtyord12(),
                getWqtyord13(),
                getWqtyord14(),
                getWqtyord15(),
                getWqtyord16(),
                getWbal1(),
                getWbal2(),
                getWbal3(),
                getWbal4(),
                getWbal5(),
                getWbal6(),
                getWbal7(),
                getWbal8(),
                getWbal9(),
                getWbal10(),
                getWbal11(),
                getWbal12(),
                getWbal13(),
                getWbal14(),
                getWbal15(),
                getWbal16());
    }
}