/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0Cr610pklQtyPerPackResponsePoutpackSze implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("PSHPNUM")
    private String pshpnum;

    @ColumnAlias("CTNTYPE")
    private String ctntype;

    @ColumnAlias("SEQCOD")
    private String seqcod;

    @ColumnAlias("ASEQNUM")
    private Short aseqnum;

    @ColumnAlias("BARCODE")
    private String barcode;

    @ColumnAlias("FROMCTN")
    private Short fromctn;

    @ColumnAlias("TOCTN")
    private Short toctn;

    @ColumnAlias("DIMDES")
    private String dimdes;

    @ColumnAlias("TOTQTY")
    private BigInteger totqty;

    @ColumnAlias("W_QTY1")
    private BigInteger wqty1;

    @ColumnAlias("W_QTY2")
    private BigInteger wqty2;

    @ColumnAlias("W_QTY3")
    private BigInteger wqty3;

    @ColumnAlias("W_QTY4")
    private BigInteger wqty4;

    @ColumnAlias("W_QTY5")
    private BigInteger wqty5;

    @ColumnAlias("W_QTY6")
    private BigInteger wqty6;

    @ColumnAlias("W_QTY7")
    private BigInteger wqty7;

    @ColumnAlias("W_QTY8")
    private BigInteger wqty8;

    @ColumnAlias("W_QTY9")
    private BigInteger wqty9;

    @ColumnAlias("W_QTY10")
    private BigInteger wqty10;

    @ColumnAlias("W_QTY11")
    private BigInteger wqty11;

    @ColumnAlias("W_QTY12")
    private BigInteger wqty12;

    @ColumnAlias("W_QTY13")
    private BigInteger wqty13;

    @ColumnAlias("W_QTY14")
    private BigInteger wqty14;

    @ColumnAlias("W_QTY15")
    private BigInteger wqty15;

    @ColumnAlias("W_QTY16")
    private BigInteger wqty16;

    @ColumnAlias("WNUMCTNS")
    private BigInteger wnumctns;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public String getCtntype() {
        return this.ctntype;
    }

    public void setCtntype(String ctntype) {
        this.ctntype = ctntype;
    }

    public String getSeqcod() {
        return this.seqcod;
    }

    public void setSeqcod(String seqcod) {
        this.seqcod = seqcod;
    }

    public Short getAseqnum() {
        return this.aseqnum;
    }

    public void setAseqnum(Short aseqnum) {
        this.aseqnum = aseqnum;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public Short getFromctn() {
        return this.fromctn;
    }

    public void setFromctn(Short fromctn) {
        this.fromctn = fromctn;
    }

    public Short getToctn() {
        return this.toctn;
    }

    public void setToctn(Short toctn) {
        this.toctn = toctn;
    }

    public String getDimdes() {
        return this.dimdes;
    }

    public void setDimdes(String dimdes) {
        this.dimdes = dimdes;
    }

    public BigInteger getTotqty() {
        return this.totqty;
    }

    public void setTotqty(BigInteger totqty) {
        this.totqty = totqty;
    }

    public BigInteger getWqty1() {
        return this.wqty1;
    }

    public void setWqty1(BigInteger wqty1) {
        this.wqty1 = wqty1;
    }

    public BigInteger getWqty2() {
        return this.wqty2;
    }

    public void setWqty2(BigInteger wqty2) {
        this.wqty2 = wqty2;
    }

    public BigInteger getWqty3() {
        return this.wqty3;
    }

    public void setWqty3(BigInteger wqty3) {
        this.wqty3 = wqty3;
    }

    public BigInteger getWqty4() {
        return this.wqty4;
    }

    public void setWqty4(BigInteger wqty4) {
        this.wqty4 = wqty4;
    }

    public BigInteger getWqty5() {
        return this.wqty5;
    }

    public void setWqty5(BigInteger wqty5) {
        this.wqty5 = wqty5;
    }

    public BigInteger getWqty6() {
        return this.wqty6;
    }

    public void setWqty6(BigInteger wqty6) {
        this.wqty6 = wqty6;
    }

    public BigInteger getWqty7() {
        return this.wqty7;
    }

    public void setWqty7(BigInteger wqty7) {
        this.wqty7 = wqty7;
    }

    public BigInteger getWqty8() {
        return this.wqty8;
    }

    public void setWqty8(BigInteger wqty8) {
        this.wqty8 = wqty8;
    }

    public BigInteger getWqty9() {
        return this.wqty9;
    }

    public void setWqty9(BigInteger wqty9) {
        this.wqty9 = wqty9;
    }

    public BigInteger getWqty10() {
        return this.wqty10;
    }

    public void setWqty10(BigInteger wqty10) {
        this.wqty10 = wqty10;
    }

    public BigInteger getWqty11() {
        return this.wqty11;
    }

    public void setWqty11(BigInteger wqty11) {
        this.wqty11 = wqty11;
    }

    public BigInteger getWqty12() {
        return this.wqty12;
    }

    public void setWqty12(BigInteger wqty12) {
        this.wqty12 = wqty12;
    }

    public BigInteger getWqty13() {
        return this.wqty13;
    }

    public void setWqty13(BigInteger wqty13) {
        this.wqty13 = wqty13;
    }

    public BigInteger getWqty14() {
        return this.wqty14;
    }

    public void setWqty14(BigInteger wqty14) {
        this.wqty14 = wqty14;
    }

    public BigInteger getWqty15() {
        return this.wqty15;
    }

    public void setWqty15(BigInteger wqty15) {
        this.wqty15 = wqty15;
    }

    public BigInteger getWqty16() {
        return this.wqty16;
    }

    public void setWqty16(BigInteger wqty16) {
        this.wqty16 = wqty16;
    }

    public BigInteger getWnumctns() {
        return this.wnumctns;
    }

    public void setWnumctns(BigInteger wnumctns) {
        this.wnumctns = wnumctns;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0Cr610pklQtyPerPackResponsePoutpackSze)) return false;
        final ProcCr1100pk0Cr610pklQtyPerPackResponsePoutpackSze procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze = (ProcCr1100pk0Cr610pklQtyPerPackResponsePoutpackSze) o;
        return Objects.equals(getOrdnum(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getOrdnum()) &&
                Objects.equals(getShpnum(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getShpnum()) &&
                Objects.equals(getPshpnum(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getPshpnum()) &&
                Objects.equals(getCtntype(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getCtntype()) &&
                Objects.equals(getSeqcod(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getSeqcod()) &&
                Objects.equals(getAseqnum(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getAseqnum()) &&
                Objects.equals(getBarcode(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getBarcode()) &&
                Objects.equals(getFromctn(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getFromctn()) &&
                Objects.equals(getToctn(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getToctn()) &&
                Objects.equals(getDimdes(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getDimdes()) &&
                Objects.equals(getTotqty(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getTotqty()) &&
                Objects.equals(getWqty1(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty1()) &&
                Objects.equals(getWqty2(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty2()) &&
                Objects.equals(getWqty3(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty3()) &&
                Objects.equals(getWqty4(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty4()) &&
                Objects.equals(getWqty5(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty5()) &&
                Objects.equals(getWqty6(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty6()) &&
                Objects.equals(getWqty7(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty7()) &&
                Objects.equals(getWqty8(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty8()) &&
                Objects.equals(getWqty9(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty9()) &&
                Objects.equals(getWqty10(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty10()) &&
                Objects.equals(getWqty11(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty11()) &&
                Objects.equals(getWqty12(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty12()) &&
                Objects.equals(getWqty13(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty13()) &&
                Objects.equals(getWqty14(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty14()) &&
                Objects.equals(getWqty15(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty15()) &&
                Objects.equals(getWqty16(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWqty16()) &&
                Objects.equals(getWnumctns(), procCr1100pk0cr610pklQtyPerPackResponsePoutpackSze.getWnumctns());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getShpnum(),
                getPshpnum(),
                getCtntype(),
                getSeqcod(),
                getAseqnum(),
                getBarcode(),
                getFromctn(),
                getToctn(),
                getDimdes(),
                getTotqty(),
                getWqty1(),
                getWqty2(),
                getWqty3(),
                getWqty4(),
                getWqty5(),
                getWqty6(),
                getWqty7(),
                getWqty8(),
                getWqty9(),
                getWqty10(),
                getWqty11(),
                getWqty12(),
                getWqty13(),
                getWqty14(),
                getWqty15(),
                getWqty16(),
                getWnumctns());
    }
}