/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr800pk0QryProvPklResponsePoutPkl implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CTNTYPE")
    private String ctntype;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("PSHPNUM")
    private String pshpnum;

    @ColumnAlias("SEQNUM")
    private Short seqnum;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("CTNDES")
    private String ctndes;

    @ColumnAlias("FROMCTN")
    private Short fromctn;

    @ColumnAlias("TOCTN")
    private Short toctn;

    @ColumnAlias("PLNGRSWGT")
    private Float plngrswgt;

    @ColumnAlias("PLNCTNWGT")
    private Float plnctnwgt;

    @ColumnAlias("PLNQTYPERCTN")
    private Integer plnqtyperctn;

    @ColumnAlias("CTNLEN")
    private Float ctnlen;

    @ColumnAlias("CTNWID")
    private Float ctnwid;

    @ColumnAlias("CTNHGT")
    private Float ctnhgt;

    @ColumnAlias("CREATID")
    private String creatid;

    @ColumnAlias("CREATDAT")
    private LocalDateTime creatdat;

    @ColumnAlias("TOTGRSWGT")
    private Double totgrswgt;

    @ColumnAlias("TOTNETWGT")
    private Double totnetwgt;

    @ColumnAlias("TOTQTY")
    private Integer totqty;

    @ColumnAlias("TOTCTN")
    private Short totctn;

    @ColumnAlias("TOTVOL")
    private Float totvol;

    @ColumnAlias("MODID")
    private String modid;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    @ColumnAlias("PROVPKLSTATUS")
    private String provpklstatus;

    @ColumnAlias("PROVPKLFINDAT")
    private String provpklfindat;

    @ColumnAlias("PROVPKLFINBY")
    private String provpklfinby;

    @ColumnAlias("CTNDIMENSION")
    private String ctndimension;

    @ColumnAlias("SKUNO")
    private String skuno;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getCtntype() {
        return this.ctntype;
    }

    public void setCtntype(String ctntype) {
        this.ctntype = ctntype;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public Short getSeqnum() {
        return this.seqnum;
    }

    public void setSeqnum(Short seqnum) {
        this.seqnum = seqnum;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getCtndes() {
        return this.ctndes;
    }

    public void setCtndes(String ctndes) {
        this.ctndes = ctndes;
    }

    public Short getFromctn() {
        return this.fromctn;
    }

    public void setFromctn(Short fromctn) {
        this.fromctn = fromctn;
    }

    public Short getToctn() {
        return this.toctn;
    }

    public void setToctn(Short toctn) {
        this.toctn = toctn;
    }

    public Float getPlngrswgt() {
        return this.plngrswgt;
    }

    public void setPlngrswgt(Float plngrswgt) {
        this.plngrswgt = plngrswgt;
    }

    public Float getPlnctnwgt() {
        return this.plnctnwgt;
    }

    public void setPlnctnwgt(Float plnctnwgt) {
        this.plnctnwgt = plnctnwgt;
    }

    public Integer getPlnqtyperctn() {
        return this.plnqtyperctn;
    }

    public void setPlnqtyperctn(Integer plnqtyperctn) {
        this.plnqtyperctn = plnqtyperctn;
    }

    public Float getCtnlen() {
        return this.ctnlen;
    }

    public void setCtnlen(Float ctnlen) {
        this.ctnlen = ctnlen;
    }

    public Float getCtnwid() {
        return this.ctnwid;
    }

    public void setCtnwid(Float ctnwid) {
        this.ctnwid = ctnwid;
    }

    public Float getCtnhgt() {
        return this.ctnhgt;
    }

    public void setCtnhgt(Float ctnhgt) {
        this.ctnhgt = ctnhgt;
    }

    public String getCreatid() {
        return this.creatid;
    }

    public void setCreatid(String creatid) {
        this.creatid = creatid;
    }

    public LocalDateTime getCreatdat() {
        return this.creatdat;
    }

    public void setCreatdat(LocalDateTime creatdat) {
        this.creatdat = creatdat;
    }

    public Double getTotgrswgt() {
        return this.totgrswgt;
    }

    public void setTotgrswgt(Double totgrswgt) {
        this.totgrswgt = totgrswgt;
    }

    public Double getTotnetwgt() {
        return this.totnetwgt;
    }

    public void setTotnetwgt(Double totnetwgt) {
        this.totnetwgt = totnetwgt;
    }

    public Integer getTotqty() {
        return this.totqty;
    }

    public void setTotqty(Integer totqty) {
        this.totqty = totqty;
    }

    public Short getTotctn() {
        return this.totctn;
    }

    public void setTotctn(Short totctn) {
        this.totctn = totctn;
    }

    public Float getTotvol() {
        return this.totvol;
    }

    public void setTotvol(Float totvol) {
        this.totvol = totvol;
    }

    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    public String getProvpklstatus() {
        return this.provpklstatus;
    }

    public void setProvpklstatus(String provpklstatus) {
        this.provpklstatus = provpklstatus;
    }

    public String getProvpklfindat() {
        return this.provpklfindat;
    }

    public void setProvpklfindat(String provpklfindat) {
        this.provpklfindat = provpklfindat;
    }

    public String getProvpklfinby() {
        return this.provpklfinby;
    }

    public void setProvpklfinby(String provpklfinby) {
        this.provpklfinby = provpklfinby;
    }

    public String getCtndimension() {
        return this.ctndimension;
    }

    public void setCtndimension(String ctndimension) {
        this.ctndimension = ctndimension;
    }

    public String getSkuno() {
        return this.skuno;
    }

    public void setSkuno(String skuno) {
        this.skuno = skuno;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr800pk0QryProvPklResponsePoutPkl)) return false;
        final ProcCr800pk0QryProvPklResponsePoutPkl procCr800pk0qryProvPklResponsePoutPkl = (ProcCr800pk0QryProvPklResponsePoutPkl) o;
        return Objects.equals(getOrdnum(), procCr800pk0qryProvPklResponsePoutPkl.getOrdnum()) &&
                Objects.equals(getCtntype(), procCr800pk0qryProvPklResponsePoutPkl.getCtntype()) &&
                Objects.equals(getShpnum(), procCr800pk0qryProvPklResponsePoutPkl.getShpnum()) &&
                Objects.equals(getPshpnum(), procCr800pk0qryProvPklResponsePoutPkl.getPshpnum()) &&
                Objects.equals(getSeqnum(), procCr800pk0qryProvPklResponsePoutPkl.getSeqnum()) &&
                Objects.equals(getClicod(), procCr800pk0qryProvPklResponsePoutPkl.getClicod()) &&
                Objects.equals(getCtndes(), procCr800pk0qryProvPklResponsePoutPkl.getCtndes()) &&
                Objects.equals(getFromctn(), procCr800pk0qryProvPklResponsePoutPkl.getFromctn()) &&
                Objects.equals(getToctn(), procCr800pk0qryProvPklResponsePoutPkl.getToctn()) &&
                Objects.equals(getPlngrswgt(), procCr800pk0qryProvPklResponsePoutPkl.getPlngrswgt()) &&
                Objects.equals(getPlnctnwgt(), procCr800pk0qryProvPklResponsePoutPkl.getPlnctnwgt()) &&
                Objects.equals(getPlnqtyperctn(), procCr800pk0qryProvPklResponsePoutPkl.getPlnqtyperctn()) &&
                Objects.equals(getCtnlen(), procCr800pk0qryProvPklResponsePoutPkl.getCtnlen()) &&
                Objects.equals(getCtnwid(), procCr800pk0qryProvPklResponsePoutPkl.getCtnwid()) &&
                Objects.equals(getCtnhgt(), procCr800pk0qryProvPklResponsePoutPkl.getCtnhgt()) &&
                Objects.equals(getCreatid(), procCr800pk0qryProvPklResponsePoutPkl.getCreatid()) &&
                Objects.equals(getCreatdat(), procCr800pk0qryProvPklResponsePoutPkl.getCreatdat()) &&
                Objects.equals(getTotgrswgt(), procCr800pk0qryProvPklResponsePoutPkl.getTotgrswgt()) &&
                Objects.equals(getTotnetwgt(), procCr800pk0qryProvPklResponsePoutPkl.getTotnetwgt()) &&
                Objects.equals(getTotqty(), procCr800pk0qryProvPklResponsePoutPkl.getTotqty()) &&
                Objects.equals(getTotctn(), procCr800pk0qryProvPklResponsePoutPkl.getTotctn()) &&
                Objects.equals(getTotvol(), procCr800pk0qryProvPklResponsePoutPkl.getTotvol()) &&
                Objects.equals(getModid(), procCr800pk0qryProvPklResponsePoutPkl.getModid()) &&
                Objects.equals(getModdat(), procCr800pk0qryProvPklResponsePoutPkl.getModdat()) &&
                Objects.equals(getProvpklstatus(), procCr800pk0qryProvPklResponsePoutPkl.getProvpklstatus()) &&
                Objects.equals(getProvpklfindat(), procCr800pk0qryProvPklResponsePoutPkl.getProvpklfindat()) &&
                Objects.equals(getProvpklfinby(), procCr800pk0qryProvPklResponsePoutPkl.getProvpklfinby()) &&
                Objects.equals(getCtndimension(), procCr800pk0qryProvPklResponsePoutPkl.getCtndimension()) &&
                Objects.equals(getSkuno(), procCr800pk0qryProvPklResponsePoutPkl.getSkuno());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getCtntype(),
                getShpnum(),
                getPshpnum(),
                getSeqnum(),
                getClicod(),
                getCtndes(),
                getFromctn(),
                getToctn(),
                getPlngrswgt(),
                getPlnctnwgt(),
                getPlnqtyperctn(),
                getCtnlen(),
                getCtnwid(),
                getCtnhgt(),
                getCreatid(),
                getCreatdat(),
                getTotgrswgt(),
                getTotnetwgt(),
                getTotqty(),
                getTotctn(),
                getTotvol(),
                getModid(),
                getModdat(),
                getProvpklstatus(),
                getProvpklfindat(),
                getProvpklfinby(),
                getCtndimension(),
                getSkuno());
    }
}