/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("MAKLCN")
    private String maklcn;

    @ColumnAlias("CLRDES")
    private String clrdes;

    @ColumnAlias("GMTDES")
    private String gmtdes;

    @ColumnAlias("W_PCKUNT")
    private Byte wpckunt;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("SSHPDAT")
    private LocalDateTime sshpdat;

    @ColumnAlias("W_MERCH_NAME")
    private String wmerchName;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    public String getClrdes() {
        return this.clrdes;
    }

    public void setClrdes(String clrdes) {
        this.clrdes = clrdes;
    }

    public String getGmtdes() {
        return this.gmtdes;
    }

    public void setGmtdes(String gmtdes) {
        this.gmtdes = gmtdes;
    }

    public Byte getWpckunt() {
        return this.wpckunt;
    }

    public void setWpckunt(Byte wpckunt) {
        this.wpckunt = wpckunt;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public LocalDateTime getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(LocalDateTime sshpdat) {
        this.sshpdat = sshpdat;
    }

    public String getWmerchName() {
        return this.wmerchName;
    }

    public void setWmerchName(String wmerchName) {
        this.wmerchName = wmerchName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList)) return false;
        final ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList = (ProcCr1100pk0GetCartoningGmtClrDetResponsePoutGmtclrList) o;
        return Objects.equals(getOrdnum(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getOrdnum()) &&
                Objects.equals(getGmtseq(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getGmtseq()) &&
                Objects.equals(getClrseq(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getClrseq()) &&
                Objects.equals(getMaklcn(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getMaklcn()) &&
                Objects.equals(getClrdes(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getClrdes()) &&
                Objects.equals(getGmtdes(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getGmtdes()) &&
                Objects.equals(getWpckunt(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getWpckunt()) &&
                Objects.equals(getClicod(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getClicod()) &&
                Objects.equals(getSshpdat(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getSshpdat()) &&
                Objects.equals(getWmerchName(), procCr1100pk0getCartoningGmtClrDetResponsePoutGmtclrList.getWmerchName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getGmtseq(),
                getClrseq(),
                getMaklcn(),
                getClrdes(),
                getGmtdes(),
                getWpckunt(),
                getClicod(),
                getSshpdat(),
                getWmerchName());
    }
}