/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcCr800pk0QryProvPklResponse implements Serializable {


    @ColumnAlias("poutPKL")
    private List<ProcCr800pk0QryProvPklResponsePoutPkl> poutPkl;

    public List<ProcCr800pk0QryProvPklResponsePoutPkl> getPoutPkl() {
        return this.poutPkl;
    }

    public void setPoutPkl(List<ProcCr800pk0QryProvPklResponsePoutPkl> poutPkl) {
        this.poutPkl = poutPkl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcCr800pk0QryProvPklResponse)) return false;
        final ProcCr800pk0QryProvPklResponse procCr800pk0qryProvPklResponse = (ProcCr800pk0QryProvPklResponse) o;
        return Objects.equals(getPoutPkl(), procCr800pk0qryProvPklResponse.getPoutPkl());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutPkl());
    }
}