/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Sy006pk0RunrepCallUrlResponse implements Serializable {


    @ColumnAlias("poutUrl")
    private String poutUrl;

    public String getPoutUrl() {
        return this.poutUrl;
    }

    public void setPoutUrl(String poutUrl) {
        this.poutUrl = poutUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Sy006pk0RunrepCallUrlResponse)) return false;
        final Sy006pk0RunrepCallUrlResponse sy006pk0runrepCallUrlResponse = (Sy006pk0RunrepCallUrlResponse) o;
        return Objects.equals(getPoutUrl(), sy006pk0runrepCallUrlResponse.getPoutUrl());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutUrl());
    }
}