/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Crt800 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`CRT800`")
@IdClass(Crt800Id.class)
public class Crt800 implements Serializable {

    private Short seqnum;
    private String shpnum;
    private String ordnum;
    private String pshpnum;
    private String ctntype;
    private Short fromctn;
    private Short toctn;
    private Float plngrswgt;
    private Float plnctnwgt;
    private Integer plnqtyperctn;
    private Float ctnlen;
    private Float ctnwid;
    private Float ctnhgt;
    private String creatid;
    private LocalDateTime creatdat;
    private Double totgrswgt;
    private Double totnetwgt;
    private Float totvol;
    private Integer totqty;
    private Short totctn;
    private String modid;
    private LocalDateTime moddat;

    @Id
    @Column(name = "`SEQNUM`", nullable = false, scale = 0, precision = 3)
    public Short getSeqnum() {
        return this.seqnum;
    }

    public void setSeqnum(Short seqnum) {
        this.seqnum = seqnum;
    }

    @Id
    @Column(name = "`SHPNUM`", nullable = false, length = 2)
    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    @Id
    @Column(name = "`ORDNUM`", nullable = false, length = 12)
    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    @Id
    @Column(name = "`PSHPNUM`", nullable = false, length = 2)
    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    @Id
    @Column(name = "`CTNTYPE`", nullable = false, length = 2)
    public String getCtntype() {
        return this.ctntype;
    }

    public void setCtntype(String ctntype) {
        this.ctntype = ctntype;
    }

    @Column(name = "`FROMCTN`", nullable = true, scale = 0, precision = 4)
    public Short getFromctn() {
        return this.fromctn;
    }

    public void setFromctn(Short fromctn) {
        this.fromctn = fromctn;
    }

    @Column(name = "`TOCTN`", nullable = true, scale = 0, precision = 4)
    public Short getToctn() {
        return this.toctn;
    }

    public void setToctn(Short toctn) {
        this.toctn = toctn;
    }

    @Column(name = "`PLNGRSWGT`", nullable = true, scale = 3, precision = 6)
    public Float getPlngrswgt() {
        return this.plngrswgt;
    }

    public void setPlngrswgt(Float plngrswgt) {
        this.plngrswgt = plngrswgt;
    }

    @Column(name = "`PLNCTNWGT`", nullable = true, scale = 3, precision = 6)
    public Float getPlnctnwgt() {
        return this.plnctnwgt;
    }

    public void setPlnctnwgt(Float plnctnwgt) {
        this.plnctnwgt = plnctnwgt;
    }

    @Column(name = "`PLNQTYPERCTN`", nullable = true, scale = 0, precision = 6)
    public Integer getPlnqtyperctn() {
        return this.plnqtyperctn;
    }

    public void setPlnqtyperctn(Integer plnqtyperctn) {
        this.plnqtyperctn = plnqtyperctn;
    }

    @Column(name = "`CTNLEN`", nullable = true, scale = 1, precision = 4)
    public Float getCtnlen() {
        return this.ctnlen;
    }

    public void setCtnlen(Float ctnlen) {
        this.ctnlen = ctnlen;
    }

    @Column(name = "`CTNWID`", nullable = true, scale = 1, precision = 4)
    public Float getCtnwid() {
        return this.ctnwid;
    }

    public void setCtnwid(Float ctnwid) {
        this.ctnwid = ctnwid;
    }

    @Column(name = "`CTNHGT`", nullable = true, scale = 1, precision = 4)
    public Float getCtnhgt() {
        return this.ctnhgt;
    }

    public void setCtnhgt(Float ctnhgt) {
        this.ctnhgt = ctnhgt;
    }

    @Column(name = "`CREATID`", nullable = true, length = 6)
    public String getCreatid() {
        return this.creatid;
    }

    public void setCreatid(String creatid) {
        this.creatid = creatid;
    }

    @Column(name = "`CREATDAT`", nullable = true)
    public LocalDateTime getCreatdat() {
        return this.creatdat;
    }

    public void setCreatdat(LocalDateTime creatdat) {
        this.creatdat = creatdat;
    }

    @Column(name = "`TOTGRSWGT`", nullable = true, scale = 3, precision = 8)
    public Double getTotgrswgt() {
        return this.totgrswgt;
    }

    public void setTotgrswgt(Double totgrswgt) {
        this.totgrswgt = totgrswgt;
    }

    @Column(name = "`TOTNETWGT`", nullable = true, scale = 3, precision = 8)
    public Double getTotnetwgt() {
        return this.totnetwgt;
    }

    public void setTotnetwgt(Double totnetwgt) {
        this.totnetwgt = totnetwgt;
    }

    @Column(name = "`TOTVOL`", nullable = true, scale = 3, precision = 7)
    public Float getTotvol() {
        return this.totvol;
    }

    public void setTotvol(Float totvol) {
        this.totvol = totvol;
    }

    @Column(name = "`TOTQTY`", nullable = true, scale = 0, precision = 6)
    public Integer getTotqty() {
        return this.totqty;
    }

    public void setTotqty(Integer totqty) {
        this.totqty = totqty;
    }

    @Column(name = "`TOTCTN`", nullable = true, scale = 0, precision = 4)
    public Short getTotctn() {
        return this.totctn;
    }

    public void setTotctn(Short totctn) {
        this.totctn = totctn;
    }

    @Column(name = "`MODID`", nullable = true, length = 6)
    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    @Column(name = "`MODDAT`", nullable = true)
    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Crt800)) return false;
        final Crt800 crt800 = (Crt800) o;
        return Objects.equals(getSeqnum(), crt800.getSeqnum()) &&
                Objects.equals(getShpnum(), crt800.getShpnum()) &&
                Objects.equals(getOrdnum(), crt800.getOrdnum()) &&
                Objects.equals(getPshpnum(), crt800.getPshpnum()) &&
                Objects.equals(getCtntype(), crt800.getCtntype());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSeqnum(),
                getShpnum(),
                getOrdnum(),
                getPshpnum(),
                getCtntype());
    }
}