/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Crt800Id implements Serializable {

    private Short seqnum;
    private String shpnum;
    private String ordnum;
    private String pshpnum;
    private String ctntype;

    public Short getSeqnum() {
        return this.seqnum;
    }

    public void setSeqnum(Short seqnum) {
        this.seqnum = seqnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public String getCtntype() {
        return this.ctntype;
    }

    public void setCtntype(String ctntype) {
        this.ctntype = ctntype;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Crt800)) return false;
        final Crt800 crt800 = (Crt800) o;
        return Objects.equals(getSeqnum(), crt800.getSeqnum()) &&
                Objects.equals(getShpnum(), crt800.getShpnum()) &&
                Objects.equals(getOrdnum(), crt800.getOrdnum()) &&
                Objects.equals(getPshpnum(), crt800.getPshpnum()) &&
                Objects.equals(getCtntype(), crt800.getCtntype());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSeqnum(),
                getShpnum(),
                getOrdnum(),
                getPshpnum(),
                getCtntype());
    }
}