/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryProvPklResponse implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CTNTYPE")
    private String ctntype;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("PSHPNUM")
    private String pshpnum;

    @ColumnAlias("SEQNUM")
    private Short seqnum;

    @ColumnAlias("FROMCTN")
    private Short fromctn;

    @ColumnAlias("TOCTN")
    private Short toctn;

    @ColumnAlias("PLNGRSWGT")
    private Float plngrswgt;

    @ColumnAlias("PLNCTNWGT")
    private Float plnctnwgt;

    @ColumnAlias("PLNQTYPERCTN")
    private Integer plnqtyperctn;

    @ColumnAlias("CTNLEN")
    private Float ctnlen;

    @ColumnAlias("CTNWID")
    private Float ctnwid;

    @ColumnAlias("CTNHGT")
    private Float ctnhgt;

    @ColumnAlias("CREATID")
    private String creatid;

    @ColumnAlias("CREATDAT")
    private LocalDateTime creatdat;

    @ColumnAlias("TOTGRSWGT")
    private Double totgrswgt;

    @ColumnAlias("TOTNETWGT")
    private Double totnetwgt;

    @ColumnAlias("TOTVOL")
    private Float totvol;

    @ColumnAlias("TOTQTY")
    private Integer totqty;

    @ColumnAlias("TOTCTN")
    private Short totctn;

    @ColumnAlias("MODID")
    private String modid;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getCtntype() {
        return this.ctntype;
    }

    public void setCtntype(String ctntype) {
        this.ctntype = ctntype;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getPshpnum() {
        return this.pshpnum;
    }

    public void setPshpnum(String pshpnum) {
        this.pshpnum = pshpnum;
    }

    public Short getSeqnum() {
        return this.seqnum;
    }

    public void setSeqnum(Short seqnum) {
        this.seqnum = seqnum;
    }

    public Short getFromctn() {
        return this.fromctn;
    }

    public void setFromctn(Short fromctn) {
        this.fromctn = fromctn;
    }

    public Short getToctn() {
        return this.toctn;
    }

    public void setToctn(Short toctn) {
        this.toctn = toctn;
    }

    public Float getPlngrswgt() {
        return this.plngrswgt;
    }

    public void setPlngrswgt(Float plngrswgt) {
        this.plngrswgt = plngrswgt;
    }

    public Float getPlnctnwgt() {
        return this.plnctnwgt;
    }

    public void setPlnctnwgt(Float plnctnwgt) {
        this.plnctnwgt = plnctnwgt;
    }

    public Integer getPlnqtyperctn() {
        return this.plnqtyperctn;
    }

    public void setPlnqtyperctn(Integer plnqtyperctn) {
        this.plnqtyperctn = plnqtyperctn;
    }

    public Float getCtnlen() {
        return this.ctnlen;
    }

    public void setCtnlen(Float ctnlen) {
        this.ctnlen = ctnlen;
    }

    public Float getCtnwid() {
        return this.ctnwid;
    }

    public void setCtnwid(Float ctnwid) {
        this.ctnwid = ctnwid;
    }

    public Float getCtnhgt() {
        return this.ctnhgt;
    }

    public void setCtnhgt(Float ctnhgt) {
        this.ctnhgt = ctnhgt;
    }

    public String getCreatid() {
        return this.creatid;
    }

    public void setCreatid(String creatid) {
        this.creatid = creatid;
    }

    public LocalDateTime getCreatdat() {
        return this.creatdat;
    }

    public void setCreatdat(LocalDateTime creatdat) {
        this.creatdat = creatdat;
    }

    public Double getTotgrswgt() {
        return this.totgrswgt;
    }

    public void setTotgrswgt(Double totgrswgt) {
        this.totgrswgt = totgrswgt;
    }

    public Double getTotnetwgt() {
        return this.totnetwgt;
    }

    public void setTotnetwgt(Double totnetwgt) {
        this.totnetwgt = totnetwgt;
    }

    public Float getTotvol() {
        return this.totvol;
    }

    public void setTotvol(Float totvol) {
        this.totvol = totvol;
    }

    public Integer getTotqty() {
        return this.totqty;
    }

    public void setTotqty(Integer totqty) {
        this.totqty = totqty;
    }

    public Short getTotctn() {
        return this.totctn;
    }

    public void setTotctn(Short totctn) {
        this.totctn = totctn;
    }

    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryProvPklResponse)) return false;
        final QryProvPklResponse qryProvPklResponse = (QryProvPklResponse) o;
        return Objects.equals(getOrdnum(), qryProvPklResponse.getOrdnum()) &&
                Objects.equals(getCtntype(), qryProvPklResponse.getCtntype()) &&
                Objects.equals(getShpnum(), qryProvPklResponse.getShpnum()) &&
                Objects.equals(getPshpnum(), qryProvPklResponse.getPshpnum()) &&
                Objects.equals(getSeqnum(), qryProvPklResponse.getSeqnum()) &&
                Objects.equals(getFromctn(), qryProvPklResponse.getFromctn()) &&
                Objects.equals(getToctn(), qryProvPklResponse.getToctn()) &&
                Objects.equals(getPlngrswgt(), qryProvPklResponse.getPlngrswgt()) &&
                Objects.equals(getPlnctnwgt(), qryProvPklResponse.getPlnctnwgt()) &&
                Objects.equals(getPlnqtyperctn(), qryProvPklResponse.getPlnqtyperctn()) &&
                Objects.equals(getCtnlen(), qryProvPklResponse.getCtnlen()) &&
                Objects.equals(getCtnwid(), qryProvPklResponse.getCtnwid()) &&
                Objects.equals(getCtnhgt(), qryProvPklResponse.getCtnhgt()) &&
                Objects.equals(getCreatid(), qryProvPklResponse.getCreatid()) &&
                Objects.equals(getCreatdat(), qryProvPklResponse.getCreatdat()) &&
                Objects.equals(getTotgrswgt(), qryProvPklResponse.getTotgrswgt()) &&
                Objects.equals(getTotnetwgt(), qryProvPklResponse.getTotnetwgt()) &&
                Objects.equals(getTotvol(), qryProvPklResponse.getTotvol()) &&
                Objects.equals(getTotqty(), qryProvPklResponse.getTotqty()) &&
                Objects.equals(getTotctn(), qryProvPklResponse.getTotctn()) &&
                Objects.equals(getModid(), qryProvPklResponse.getModid()) &&
                Objects.equals(getModdat(), qryProvPklResponse.getModdat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getCtntype(),
                getShpnum(),
                getPshpnum(),
                getSeqnum(),
                getFromctn(),
                getToctn(),
                getPlngrswgt(),
                getPlnctnwgt(),
                getPlnqtyperctn(),
                getCtnlen(),
                getCtnwid(),
                getCtnhgt(),
                getCreatid(),
                getCreatdat(),
                getTotgrswgt(),
                getTotnetwgt(),
                getTotvol(),
                getTotqty(),
                getTotctn(),
                getModid(),
                getModdat());
    }
}