/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryShpnumResponse implements Serializable {


    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("SHPDST")
    private String shpdst;

    @ColumnAlias("CLIONUM")
    private String clionum;

    @ColumnAlias("CLIPCKTYP")
    private String clipcktyp;

    @ColumnAlias("CMTPACKINGTYPE")
    private String cmtpackingtype;

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public String getShpdst() {
        return this.shpdst;
    }

    public void setShpdst(String shpdst) {
        this.shpdst = shpdst;
    }

    public String getClionum() {
        return this.clionum;
    }

    public void setClionum(String clionum) {
        this.clionum = clionum;
    }

    public String getClipcktyp() {
        return this.clipcktyp;
    }

    public void setClipcktyp(String clipcktyp) {
        this.clipcktyp = clipcktyp;
    }

    public String getCmtpackingtype() {
        return this.cmtpackingtype;
    }

    public void setCmtpackingtype(String cmtpackingtype) {
        this.cmtpackingtype = cmtpackingtype;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryShpnumResponse)) return false;
        final QryShpnumResponse qryShpnumResponse = (QryShpnumResponse) o;
        return Objects.equals(getShpnum(), qryShpnumResponse.getShpnum()) &&
                Objects.equals(getShpdst(), qryShpnumResponse.getShpdst()) &&
                Objects.equals(getClionum(), qryShpnumResponse.getClionum()) &&
                Objects.equals(getClipcktyp(), qryShpnumResponse.getClipcktyp()) &&
                Objects.equals(getCmtpackingtype(), qryShpnumResponse.getCmtpackingtype());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShpnum(),
                getShpdst(),
                getClionum(),
                getClipcktyp(),
                getCmtpackingtype());
    }
}