/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.mu.cmt.pfs.pfsdb.models.query.*;

public interface PfsdbQueryExecutorService {

    Page<QryProvPklResponse> executeQryProvPKL(String pordnum, String pshpnum, String ppshpnum, Pageable pageable);

    void exportQryProvPKL(String pordnum, String pshpnum, String ppshpnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryPartShpCreateEditProvPklResponse> executeQryPartShpCreateEditProvPKL(String pordnum, String pshpnum, String poperation, Pageable pageable);

    void exportQryPartShpCreateEditProvPKL(String pordnum, String pshpnum, String poperation, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryCheckUserAccessResponse executeQryCheckUserAccess(String pordnum, String pshpnum, String ppshpnum);

    Page<QryGetPartShpnumResponse> executeQryGetPartShpnum(String pordnum, String pshpnum, Pageable pageable);

    void exportQryGetPartShpnum(String pordnum, String pshpnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryGetShpDetailsResponse executeQryGetShpDetails(String pordnum, String pshpnum);

    Page<QryPartShpWipResponse> executeQryPartShpWIP(String pordnum, String pshpnum, Pageable pageable);

    void exportQryPartShpWIP(String pordnum, String pshpnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryCallFmbPathResponse executeQryCallFmbPath(String pfmbprogid, String potherParams);

    Page<QryShpnumResponse> executeQryShpnum(String pordnum, Pageable pageable);

    void exportQryShpnum(String pordnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}